// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

export const userReports = [
    {
        id: 'td46fnya1pdkff6c8knaa43toh',
        username: 'aaron.allen',
        email: 'user-758@sample.mattermost.com',
        create_at: 1702455668778,
        display_name: 'Aaron Allen',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'jhicffki17f8bxft8a1zf1bs5e',
        username: 'aaron.carroll',
        email: 'user-15@sample.mattermost.com',
        create_at: 1702455571548,
        display_name: 'Aaron Carroll',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'n9zy3pmd9bgctnzn9aga1cxcxy',
        username: 'aaron.chapman',
        email: 'user-684@sample.mattermost.com',
        create_at: 1702455668047,
        display_name: 'Aaron Chapman',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'xrawxfx19pdkzftt7r77dwwi1h',
        username: 'aaron.cruz',
        email: 'user-404@sample.mattermost.com',
        create_at: 1702455665362,
        display_name: 'Aaron Cruz',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'ih8kn9y8ztfjpk3ry4khcuodcr',
        username: 'aaron.fowler',
        email: 'user-932@sample.mattermost.com',
        create_at: 1702455670503,
        display_name: 'Zoonoodle',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'tte3o6bab7ybjnua15w6ui5e4h',
        username: 'aaron.howard',
        email: 'user-639@sample.mattermost.com',
        create_at: 1702455667603,
        display_name: 'Aaron Howard',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'q8pi6tx6kig73r6ozpm3zx7ujo',
        username: 'aaron.hudson',
        email: 'user-204@sample.mattermost.com',
        create_at: 1702455663486,
        display_name: 'Aaron Hudson',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'kt86ck178irijpymox1bpbbrcy',
        username: 'aaron.torres',
        email: 'user-545@sample.mattermost.com',
        create_at: 1702455666713,
        display_name: 'Mydo',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: '4wk4qzwkmjy18mbqu88f31js7r',
        username: 'adam.frazier',
        email: 'user-98@sample.mattermost.com',
        create_at: 1702455617502,
        display_name: 'Jabbertype',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 't8wurmkheinp9mwzxwprkfxinr',
        username: 'adam.gibson',
        email: 'user-378@sample.mattermost.com',
        create_at: 1702455665156,
        display_name: 'Bubbletube',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'tnoui5iyifbfmb9md7zmb3qzec',
        username: 'adam.lee',
        email: 'user-480@sample.mattermost.com',
        create_at: 1702455666091,
        display_name: 'Adam Lee',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'bw8rzndc8jnwfrqjuxytmqtx1o',
        username: 'adam.mitchell',
        email: 'user-427@sample.mattermost.com',
        create_at: 1702455665608,
        display_name: 'Adam Mitchell',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'otqrwima1byeip6fpnp377txyh',
        username: 'adam.myers',
        email: 'user-142@sample.mattermost.com',
        create_at: 1702455662907,
        display_name: 'Adam Myers',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'djwi8pn3m7yb5x597dea5ty1by',
        username: 'adam.rivera',
        email: 'user-133@sample.mattermost.com',
        create_at: 1702455662834,
        display_name: 'Quimba',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 't9cefzupt7f6ujg3wpgyofozjh',
        username: 'adam.ross',
        email: 'user-572@sample.mattermost.com',
        create_at: 1702455666983,
        display_name: 'Adam Ross',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'awkjao9dc3yauqbj4zhpg7mcne',
        username: 'alan.hayes',
        email: 'user-500@sample.mattermost.com',
        create_at: 1702455666288,
        display_name: 'Alan Hayes',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'df46cz5acpbyjbh5yotu44awco',
        username: 'alan.james',
        email: 'user-778@sample.mattermost.com',
        create_at: 1702455668997,
        display_name: 'Alan James',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'fsq4ehcfftn5tm988zpxnb1uke',
        username: 'alan.lynch',
        email: 'user-432@sample.mattermost.com',
        create_at: 1702455665633,
        display_name: 'Alan Lynch',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'bbx4qpojr381deyyg3kgt146aa',
        username: 'albert.chapman',
        email: 'user-891@sample.mattermost.com',
        create_at: 1702455670082,
        display_name: 'Albert Chapman',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'ind86yn3xpyjte3wa1qr937mer',
        username: 'albert.harvey',
        email: 'user-574@sample.mattermost.com',
        create_at: 1702455666994,
        display_name: 'Albert Harvey',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'sfg8ys5jziy17ybinoyf5mdtuc',
        username: 'albert.shaw',
        email: 'user-812@sample.mattermost.com',
        create_at: 1702455669304,
        display_name: 'Jabberbean',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'fo3xbzz3x7buff7i4ozcsjk4ye',
        username: 'albert.stone',
        email: 'user-555@sample.mattermost.com',
        create_at: 1702455666822,
        display_name: 'Albert Stone',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'k7cm5zpohbgi5q4hn35f9xqyyo',
        username: 'albert.sullivan',
        email: 'user-428@sample.mattermost.com',
        create_at: 1702455665612,
        display_name: 'Skyvu',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'msma1au7ei8f8m8gnefke1rd4y',
        username: 'albert.warren',
        email: 'user-381@sample.mattermost.com',
        create_at: 1702455665178,
        display_name: 'Albert Warren',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'oprkfhh7yiduxndsowft8dbwfe',
        username: 'alice.matthews',
        email: 'user-51@sample.mattermost.com',
        create_at: 1702455572002,
        display_name: 'Alice Matthews',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'umpn8ig67jgbiekag8en1e98pw',
        username: 'alice.moore',
        email: 'user-392@sample.mattermost.com',
        create_at: 1702455665274,
        display_name: 'Alice Moore',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'zp36k8wifjr6pxmktoyz6yox1r',
        username: 'amanda.armstrong',
        email: 'user-127@sample.mattermost.com',
        create_at: 1702455617641,
        display_name: 'Amanda Armstrong',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'n6zyy4gtjpnfdped88acr9utdh',
        username: 'amanda.burns',
        email: 'user-829@sample.mattermost.com',
        create_at: 1702455669488,
        display_name: 'Amanda Burns',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'nhpudp95yjbpufhucqf9ffh8mw',
        username: 'amanda.gomez',
        email: 'user-961@sample.mattermost.com',
        create_at: 1702455670808,
        display_name: 'Amanda Gomez',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'apudekind3b97dbfk6i7hej65e',
        username: 'amanda.little',
        email: 'user-43@sample.mattermost.com',
        create_at: 1702455571865,
        display_name: 'Amanda Little',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'zetqjuj9rpnhmpaaat39zn517e',
        username: 'amanda.murphy',
        email: 'user-395@sample.mattermost.com',
        create_at: 1702455665310,
        display_name: 'Amanda Murphy',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'yy1s1hifibr9unzikck3i9p7ae',
        username: 'amy.greene',
        email: 'user-861@sample.mattermost.com',
        create_at: 1702455669801,
        display_name: 'Amy Greene',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'kdyw849fntyu7qg33eupzik5sy',
        username: 'amy.montgomery',
        email: 'user-854@sample.mattermost.com',
        create_at: 1702455669734,
        display_name: 'Tagfeed',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: '8xf383r7hfrp9qhw6gf9o8ss6e',
        username: 'amy.olson',
        email: 'user-495@sample.mattermost.com',
        create_at: 1702455666242,
        display_name: 'Amy Olson',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'pnkodupzapbez87sd4ugcoqn6e',
        username: 'amy.patterson',
        email: 'user-301@sample.mattermost.com',
        create_at: 1702455664427,
        display_name: 'Amy Patterson',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'jseaw1k6z3yxtg6zdpkbjqmy6w',
        username: 'amy.rice',
        email: 'user-938@sample.mattermost.com',
        create_at: 1702455670554,
        display_name: 'Amy Rice',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'b69bknt9n7yhxbftkbex4zmhqr',
        username: 'andrea.ellis',
        email: 'user-391@sample.mattermost.com',
        create_at: 1702455665261,
        display_name: 'Buzzdog',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'zrpmtjn5778hbfyfcmf1aq3hko',
        username: 'andrea.mendoza',
        email: 'user-780@sample.mattermost.com',
        create_at: 1702455669001,
        display_name: 'Gigashots',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'f5bxj5ekointbfqeiadzn656cy',
        username: 'andrea.morales',
        email: 'user-248@sample.mattermost.com',
        create_at: 1702455663893,
        display_name: 'Andrea Morales',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'ncjsmmostinpux7oq3kf6yjebc',
        username: 'andrea.scott',
        email: 'user-579@sample.mattermost.com',
        create_at: 1702455667038,
        display_name: 'Andrea Scott',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'kdsxg49babyf7g7fdgod455hoe',
        username: 'andrew.hayes',
        email: 'user-853@sample.mattermost.com',
        create_at: 1702455669724,
        display_name: 'Andrew Hayes',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'utm86nzo43dhpkdzqoadsufkro',
        username: 'andrew.jenkins',
        email: 'user-838@sample.mattermost.com',
        create_at: 1702455669573,
        display_name: 'Andrew Jenkins',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'dygx7tjumjrqjytpkt4yc7wzio',
        username: 'andrew.owens',
        email: 'user-903@sample.mattermost.com',
        create_at: 1702455670220,
        display_name: 'Andrew Owens',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'sbzkoutqbpnsikhrzaweyxegyc',
        username: 'andrew.stewart',
        email: 'user-531@sample.mattermost.com',
        create_at: 1702455666572,
        display_name: 'Andrew Stewart',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'iqxf1gajsfgq38h69fhkzz94wh',
        username: 'angela.baker',
        email: 'user-161@sample.mattermost.com',
        create_at: 1702455663124,
        display_name: 'Angela Baker',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'jzk6ucm5tinyzmykte9xrido7c',
        username: 'anna.boyd',
        email: 'user-565@sample.mattermost.com',
        create_at: 1702455666922,
        display_name: 'Anna Boyd',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'qs8jryteg3g6te7mtwj33kg4kh',
        username: 'anna.harrison',
        email: 'user-164@sample.mattermost.com',
        create_at: 1702455663127,
        display_name: 'Anna Harrison',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'fq8fohidk3gt3d7dqjers8gr5c',
        username: 'anna.moore',
        email: 'user-110@sample.mattermost.com',
        create_at: 1702455617550,
        display_name: 'Devify',
        roles: 'system_admin system_user',
        days_active: 0,
    },
    {
        id: 'kon88k7xrbdtdj9ee9ryk95bcy',
        username: 'anna.payne',
        email: 'user-426@sample.mattermost.com',
        create_at: 1702455665600,
        display_name: 'Anna Payne',
        roles: 'system_user',
        days_active: 0,
    },
    {
        id: 'fw4zxd3sibg45yqbmjkhujejho',
        username: 'anna.perkins',
        email: 'user-775@sample.mattermost.com',
        create_at: 1702455668951,
        display_name: 'Anna Perkins',
        roles: 'system_admin system_user',
        days_active: 0,
    },
];
