// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by "make generate-worktemplates"
// DO NOT EDIT

package worktemplates

func init() {
	registerWorkTemplateCategory("product_teams", wtc846b565cd80043537945134a54812e07)
	registerWorkTemplate("product_teams/feature_release:v1", wt00a1b44a5831c0a3acb14787b3fdd352)
	registerWorkTemplate("product_teams/some_other_usecase:v1", wt1e50a5b712f2155cfa93d564c0067eed)

	// Register categories strings
	_ = T("worktemplate.category.product_teams")

	// Register translation strings
	_ = T("worktemplate.product_teams.description.channel")
	_ = T("worktemplate.other_usecase.description.channel")
	_ = T("worktemplate.other_usecase.description.playbook")
}

var wtc846b565cd80043537945134a54812e07 = &WorkTemplateCategory{
	ID:   "product_teams",
	Name: "worktemplate.category.product_teams",
}

var wt00a1b44a5831c0a3acb14787b3fdd352 = &WorkTemplate{
	ID:           "product_teams/feature_release:v1",
	Category:     "product_teams",
	UseCase:      "Feature Release",
	Illustration: "/images/illustrations/feature-release.png",
	Visibility:   "public",
	FeatureFlag: &FeatureFlag{
		Name:  "feature_release_work_template",
		Value: "on",
	},
	Description: Description{
		Channel: &TranslatableString{
			ID:             "worktemplate.product_teams.description.channel",
			DefaultMessage: "This is the channels section description",
			Illustration:   "",
		},
		Board: &TranslatableString{
			ID:             "",
			DefaultMessage: "This is the boards section description",
			Illustration:   "",
		},
		Playbook: &TranslatableString{
			ID:             "",
			DefaultMessage: "This is the playbooks section description",
			Illustration:   "",
		},
		Integration: &TranslatableString{
			ID:             "",
			DefaultMessage: "This is the integrations section description",
			Illustration:   "/images/worktemplates/integrations/jira-github.png",
		},
	},
	Content: []Content{
		{
			Channel: &Channel{
				ID:           "feature-release",
				Name:         "feature release channel",
				Purpose:      "this channel is for the feature release team.",
				Playbook:     "product-release-playbook",
				Illustration: "/images/worktemplates/channels/feature-release.png",
			},
		},
		{
			Board: &Board{
				ID:           "board-meeting-agenda",
				Template:     "meeting agenda|bwps66irhr7b9dxgayf9kz33g5o",
				Name:         "meeting agenda board",
				Channel:      "feature-release",
				Illustration: "/images/worktemplates/boards/meeting-agenda.png",
			},
		},
		{
			Board: &Board{
				ID:           "board-project-task",
				Template:     "project task|bmttiziw35irgtmztewd9upyqdy",
				Name:         "project task board",
				Channel:      "feature-release",
				Illustration: "/images/worktemplates/boards/project-task.png",
			},
		},
		{
			Playbook: &Playbook{
				Template:     "product release",
				Name:         "feature release playbook",
				ID:           "product-release-playbook",
				Illustration: "/images/worktemplates/boards/project-task.png",
			},
		},
		{
			Integration: &Integration{
				ID: "marketplace-plugin-jira",
			},
		},
		{
			Integration: &Integration{
				ID: "marketplace-plugin-github",
			},
		},
	},
}

var wt1e50a5b712f2155cfa93d564c0067eed = &WorkTemplate{
	ID:           "product_teams/some_other_usecase:v1",
	Category:     "product_teams",
	UseCase:      "Other use case",
	Illustration: "/images/illustrations/feature-release.png",
	Visibility:   "public",

	Description: Description{
		Channel: &TranslatableString{
			ID:             "worktemplate.other_usecase.description.channel",
			DefaultMessage: "This is the channels section description",
			Illustration:   "",
		},
		Board: &TranslatableString{
			ID:             "",
			DefaultMessage: "This is the boards section description",
			Illustration:   "",
		},
		Playbook: &TranslatableString{
			ID:             "worktemplate.other_usecase.description.playbook",
			DefaultMessage: "This is the playbooks section description",
			Illustration:   "",
		},
		Integration: &TranslatableString{
			ID:             "",
			DefaultMessage: "This is the integrations section description",
			Illustration:   "/images/worktemplates/integrations/jira-github.png",
		},
	},
	Content: []Content{
		{
			Channel: &Channel{
				ID:           "feature-release",
				Name:         "feature release channel",
				Purpose:      "this channel is for the feature release team.",
				Playbook:     "product-release-playbook",
				Illustration: "/images/worktemplates/channels/feature-release.png",
			},
		},
		{
			Board: &Board{
				ID:           "board-meeting-agenda",
				Template:     "meeting agenda|bwps66irhr7b9dxgayf9kz33g5o",
				Name:         "meeting agenda board",
				Channel:      "feature-release",
				Illustration: "/images/worktemplates/boards/meeting-agenda.png",
			},
		},
		{
			Board: &Board{
				ID:           "board-project-task",
				Template:     "project task|bmttiziw35irgtmztewd9upyqdy",
				Name:         "project task board",
				Channel:      "feature-release",
				Illustration: "/images/worktemplates/boards/project-task.png",
			},
		},
		{
			Playbook: &Playbook{
				Template:     "product release",
				Name:         "feature release playbook",
				ID:           "product-release-playbook",
				Illustration: "/images/worktemplates/boards/project-task.png",
			},
		},
		{
			Integration: &Integration{
				ID: "marketplace-plugin-jira",
			},
		},
		{
			Integration: &Integration{
				ID: "marketplace-plugin-github",
			},
		},
	},
}
