// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import {
    mdiAccount,
    mdiAccountGroup,
    mdiAccountMultiple,
    mdiAlert,
    mdiAlertCircle,
    mdiApi,
    mdiArchive,
    mdiArrowRight,
    mdiAt,
    mdiBell,
    mdiBellRing,
    mdiBook,
    mdiBookmark,
    mdiBriefcase,
    mdiBug,
    mdiBullhorn,
    mdiCalendar,
    mdiCamera,
    mdiCart,
    mdiCat,
    mdiChartBar,
    mdiChartLine,
    mdiChat,
    mdiCheck,
    mdiCheckCircle,
    mdiChevronRight,
    mdiClipboard,
    mdiClock,
    mdiClose,
    mdiCloud,
    mdiCodeBraces,
    mdiCodeTags,
    mdiCog,
    mdiComment,
    mdiConsole,
    mdiCreditCard,
    mdiCube,
    mdiDatabase,
    mdiDog,
    mdiDotsHorizontal,
    mdiDownload,
    mdiEarth,
    mdiEmail,
    mdiEmoticon,
    mdiEmoticonHappy,
    mdiEye,
    mdiFile,
    mdiFileDocument,
    mdiFilter,
    mdiFire,
    mdiFlag,
    mdiFlash,
    mdiFlask,
    mdiFlower,
    mdiFolder,
    mdiForum,
    mdiGamepad,
    mdiGift,
    mdiGithub,
    mdiGlasses,
    mdiHammer,
    mdiHandshake,
    mdiHeart,
    mdiHelp,
    mdiHelpCircle,
    mdiHistory,
    mdiHome,
    mdiImage,
    mdiInformation,
    mdiKey,
    mdiLaptop,
    mdiLeaf,
    mdiLightbulb,
    mdiLightningBolt,
    mdiLink,
    mdiLock,
    mdiMagnify,
    mdiMap,
    mdiMapMarker,
    mdiMedal,
    mdiMenu,
    mdiMessage,
    mdiMessageText,
    mdiMicrophone,
    mdiMinus,
    mdiMonitor,
    mdiMovie,
    mdiMusic,
    mdiNewspaper,
    mdiOfficeBuilding,
    mdiPackage,
    mdiPalette,
    mdiPaperclip,
    mdiPaw,
    mdiPencil,
    mdiPhone,
    mdiPin,
    mdiPlay,
    mdiPlus,
    mdiPlusCircle,
    mdiPodcast,
    mdiPoll,
    mdiPresentation,
    mdiPrinter,
    mdiPuzzle,
    mdiRadio,
    mdiRefresh,
    mdiRocket,
    mdiRss,
    mdiSafe,
    mdiSchool,
    mdiSecurity,
    mdiSend,
    mdiServer,
    mdiShare,
    mdiShield,
    mdiShopping,
    mdiStar,
    mdiStore,
    mdiSync,
    mdiTable,
    mdiTag,
    mdiTarget,
    mdiTelevision,
    mdiTestTube,
    mdiText,
    mdiThumbUp,
    mdiTicket,
    mdiTimer,
    mdiTools,
    mdiTrashCan,
    mdiTree,
    mdiTrendingUp,
    mdiTrophy,
    mdiTruck,
    mdiTune,
    mdiUmbrella,
    mdiUpload,
    mdiVideo,
    mdiVolumeHigh,
    mdiWallet,
    mdiWater,
    mdiWeatherCloudy,
    mdiWeatherLightning,
    mdiWeatherSunny,
    mdiWeb,
    mdiWeight,
    mdiWifi,
    mdiWrench,
    mdiYoutube,
} from '@mdi/js';

import type {IconLibrary} from './types';

// Map of icon names to their SVG paths
const MDI_ICON_MAP: Record<string, string> = {
    'account': mdiAccount,
    'account-group': mdiAccountGroup,
    'account-multiple': mdiAccountMultiple,
    'alert': mdiAlert,
    'alert-circle': mdiAlertCircle,
    'api': mdiApi,
    'archive': mdiArchive,
    'arrow-right': mdiArrowRight,
    'at': mdiAt,
    'bell': mdiBell,
    'bell-ring': mdiBellRing,
    'book': mdiBook,
    'bookmark': mdiBookmark,
    'briefcase': mdiBriefcase,
    'bug': mdiBug,
    'bullhorn': mdiBullhorn,
    'calendar': mdiCalendar,
    'camera': mdiCamera,
    'cart': mdiCart,
    'cat': mdiCat,
    'chart-bar': mdiChartBar,
    'chart-line': mdiChartLine,
    'chat': mdiChat,
    'check': mdiCheck,
    'check-circle': mdiCheckCircle,
    'chevron-right': mdiChevronRight,
    'clipboard': mdiClipboard,
    'clock': mdiClock,
    'close': mdiClose,
    'cloud': mdiCloud,
    'code-tags': mdiCodeTags,
    'code-braces': mdiCodeBraces,
    'cog': mdiCog,
    'comment': mdiComment,
    'console': mdiConsole,
    'credit-card': mdiCreditCard,
    'cube': mdiCube,
    'database': mdiDatabase,
    'dog': mdiDog,
    'dots-horizontal': mdiDotsHorizontal,
    'download': mdiDownload,
    'earth': mdiEarth,
    'email': mdiEmail,
    'emoticon': mdiEmoticon,
    'emoticon-happy': mdiEmoticonHappy,
    'eye': mdiEye,
    'file': mdiFile,
    'file-document': mdiFileDocument,
    'filter': mdiFilter,
    'fire': mdiFire,
    'flag': mdiFlag,
    'flash': mdiFlash,
    'flask': mdiFlask,
    'flower': mdiFlower,
    'folder': mdiFolder,
    'forum': mdiForum,
    'gamepad': mdiGamepad,
    'gift': mdiGift,
    'github': mdiGithub,
    'glasses': mdiGlasses,
    'web': mdiWeb,
    'hammer': mdiHammer,
    'handshake': mdiHandshake,
    'heart': mdiHeart,
    'help': mdiHelp,
    'help-circle': mdiHelpCircle,
    'history': mdiHistory,
    'home': mdiHome,
    'image': mdiImage,
    'information': mdiInformation,
    'key': mdiKey,
    'laptop': mdiLaptop,
    'leaf': mdiLeaf,
    'lightbulb': mdiLightbulb,
    'lightning-bolt': mdiLightningBolt,
    'link': mdiLink,
    'lock': mdiLock,
    'magnify': mdiMagnify,
    'map': mdiMap,
    'map-marker': mdiMapMarker,
    'medal': mdiMedal,
    'menu': mdiMenu,
    'message': mdiMessage,
    'message-text': mdiMessageText,
    'microphone': mdiMicrophone,
    'minus': mdiMinus,
    'monitor': mdiMonitor,
    'movie': mdiMovie,
    'music': mdiMusic,
    'newspaper': mdiNewspaper,
    'office-building': mdiOfficeBuilding,
    'package': mdiPackage,
    'palette': mdiPalette,
    'paperclip': mdiPaperclip,
    'paw': mdiPaw,
    'pencil': mdiPencil,
    'phone': mdiPhone,
    'pin': mdiPin,
    'play': mdiPlay,
    'plus': mdiPlus,
    'plus-circle': mdiPlusCircle,
    'podcast': mdiPodcast,
    'poll': mdiPoll,
    'presentation': mdiPresentation,
    'printer': mdiPrinter,
    'puzzle': mdiPuzzle,
    'radio': mdiRadio,
    'refresh': mdiRefresh,
    'rocket': mdiRocket,
    'rss': mdiRss,
    'safe': mdiSafe,
    'school': mdiSchool,
    'security': mdiSecurity,
    'send': mdiSend,
    'server': mdiServer,
    'share': mdiShare,
    'shield': mdiShield,
    'shopping': mdiShopping,
    'star': mdiStar,
    'store': mdiStore,
    'sync': mdiSync,
    'table': mdiTable,
    'tag': mdiTag,
    'target': mdiTarget,
    'television': mdiTelevision,
    'test-tube': mdiTestTube,
    'text': mdiText,
    'thumb-up': mdiThumbUp,
    'ticket': mdiTicket,
    'timer': mdiTimer,
    'tools': mdiTools,
    'trash-can': mdiTrashCan,
    'tree': mdiTree,
    'trending-up': mdiTrendingUp,
    'trophy': mdiTrophy,
    'truck': mdiTruck,
    'tune': mdiTune,
    'umbrella': mdiUmbrella,
    'upload': mdiUpload,
    'video': mdiVideo,
    'volume-high': mdiVolumeHigh,
    'wallet': mdiWallet,
    'water': mdiWater,
    'weather-cloudy': mdiWeatherCloudy,
    'weather-lightning': mdiWeatherLightning,
    'weather-sunny': mdiWeatherSunny,
    'weight': mdiWeight,
    'wifi': mdiWifi,
    'wrench': mdiWrench,
    'youtube': mdiYoutube,
};

export function getMdiIconPath(name: string): string | undefined {
    return MDI_ICON_MAP[name];
}

export const mdiLibrary: IconLibrary = {
    id: 'mdi',
    name: 'Material Design',
    prefix: 'mdi:',
    categories: [
        {
            id: 'general',
            name: 'General',
            icons: [
                {name: 'web', path: mdiWeb},
                {name: 'earth', path: mdiEarth},
                {name: 'star', path: mdiStar},
                {name: 'heart', path: mdiHeart},
                {name: 'bookmark', path: mdiBookmark},
                {name: 'flag', path: mdiFlag},
                {name: 'fire', path: mdiFire},
                {name: 'lightning-bolt', path: mdiLightningBolt},
                {name: 'flash', path: mdiFlash},
                {name: 'flash', path: mdiFlash},
                {name: 'lock', path: mdiLock},
                {name: 'key', path: mdiKey},
                {name: 'eye', path: mdiEye},
                {name: 'link', path: mdiLink},
                {name: 'pin', path: mdiPin},
                {name: 'tag', path: mdiTag},
            ],
        },
        {
            id: 'communication',
            name: 'Communication',
            icons: [
                {name: 'message', path: mdiMessage},
                {name: 'message-text', path: mdiMessageText},
                {name: 'chat', path: mdiChat},
                {name: 'comment', path: mdiComment},
                {name: 'forum', path: mdiForum},
                {name: 'email', path: mdiEmail},
                {name: 'at', path: mdiAt},
                {name: 'phone', path: mdiPhone},
                {name: 'bell', path: mdiBell},
                {name: 'bell-ring', path: mdiBellRing},
                {name: 'bullhorn', path: mdiBullhorn},
                {name: 'send', path: mdiSend},
                {name: 'share', path: mdiShare},
                {name: 'rss', path: mdiRss},
                {name: 'podcast', path: mdiPodcast},
                {name: 'radio', path: mdiRadio},
            ],
        },
        {
            id: 'work',
            name: 'Work & Business',
            icons: [
                {name: 'briefcase', path: mdiBriefcase},
                {name: 'office-building', path: mdiOfficeBuilding},
                {name: 'calendar', path: mdiCalendar},
                {name: 'clock', path: mdiClock},
                {name: 'timer', path: mdiTimer},
                {name: 'clipboard', path: mdiClipboard},
                {name: 'file', path: mdiFile},
                {name: 'file-document', path: mdiFileDocument},
                {name: 'folder', path: mdiFolder},
                {name: 'chart-bar', path: mdiChartBar},
                {name: 'chart-line', path: mdiChartLine},
                {name: 'trending-up', path: mdiTrendingUp},
                {name: 'poll', path: mdiPoll},
                {name: 'presentation', path: mdiPresentation},
                {name: 'target', path: mdiTarget},
                {name: 'trophy', path: mdiTrophy},
                {name: 'medal', path: mdiMedal},
                {name: 'handshake', path: mdiHandshake},
            ],
        },
        {
            id: 'development',
            name: 'Development',
            icons: [
                {name: 'code-tags', path: mdiCodeTags},
                {name: 'code-tags', path: mdiCodeTags},
                {name: 'code-braces', path: mdiCodeBraces},
                {name: 'console', path: mdiConsole},
                {name: 'api', path: mdiApi},
                {name: 'database', path: mdiDatabase},
                {name: 'server', path: mdiServer},
                {name: 'bug', path: mdiBug},
                {name: 'flask', path: mdiFlask},
                {name: 'test-tube', path: mdiTestTube},
                {name: 'cog', path: mdiCog},
                {name: 'tune', path: mdiTune},
                {name: 'wrench', path: mdiWrench},
                {name: 'hammer', path: mdiHammer},
                {name: 'tools', path: mdiTools},
                {name: 'github', path: mdiGithub},
                {name: 'web', path: mdiWeb},
                {name: 'rocket', path: mdiRocket},
            ],
        },
        {
            id: 'media',
            name: 'Media & Entertainment',
            icons: [
                {name: 'image', path: mdiImage},
                {name: 'camera', path: mdiCamera},
                {name: 'video', path: mdiVideo},
                {name: 'movie', path: mdiMovie},
                {name: 'music', path: mdiMusic},
                {name: 'microphone', path: mdiMicrophone},
                {name: 'volume-high', path: mdiVolumeHigh},
                {name: 'play', path: mdiPlay},
                {name: 'gamepad', path: mdiGamepad},
                {name: 'television', path: mdiTelevision},
                {name: 'youtube', path: mdiYoutube},
                {name: 'newspaper', path: mdiNewspaper},
                {name: 'book', path: mdiBook},
            ],
        },
        {
            id: 'people',
            name: 'People & Social',
            icons: [
                {name: 'account', path: mdiAccount},
                {name: 'account-multiple', path: mdiAccountMultiple},
                {name: 'account-group', path: mdiAccountGroup},
                {name: 'emoticon', path: mdiEmoticon},
                {name: 'emoticon-happy', path: mdiEmoticonHappy},
                {name: 'thumb-up', path: mdiThumbUp},
            ],
        },
        {
            id: 'nature',
            name: 'Nature & Animals',
            icons: [
                {name: 'leaf', path: mdiLeaf},
                {name: 'flower', path: mdiFlower},
                {name: 'tree', path: mdiTree},
                {name: 'water', path: mdiWater},
                {name: 'weather-sunny', path: mdiWeatherSunny},
                {name: 'weather-cloudy', path: mdiWeatherCloudy},
                {name: 'weather-lightning', path: mdiWeatherLightning},
                {name: 'paw', path: mdiPaw},
                {name: 'cat', path: mdiCat},
                {name: 'dog', path: mdiDog},
            ],
        },
        {
            id: 'objects',
            name: 'Objects',
            icons: [
                {name: 'lightbulb', path: mdiLightbulb},
                {name: 'gift', path: mdiGift},
                {name: 'cube', path: mdiCube},
                {name: 'puzzle', path: mdiPuzzle},
                {name: 'palette', path: mdiPalette},
                {name: 'pencil', path: mdiPencil},
                {name: 'glasses', path: mdiGlasses},
                {name: 'umbrella', path: mdiUmbrella},
                {name: 'package', path: mdiPackage},
                {name: 'ticket', path: mdiTicket},
                {name: 'credit-card', path: mdiCreditCard},
                {name: 'wallet', path: mdiWallet},
            ],
        },
        {
            id: 'places',
            name: 'Places & Travel',
            icons: [
                {name: 'home', path: mdiHome},
                {name: 'store', path: mdiStore},
                {name: 'school', path: mdiSchool},
                {name: 'map', path: mdiMap},
                {name: 'map-marker', path: mdiMapMarker},
                {name: 'truck', path: mdiTruck},
                {name: 'cloud', path: mdiCloud},
            ],
        },
        {
            id: 'devices',
            name: 'Devices & Tech',
            icons: [
                {name: 'laptop', path: mdiLaptop},
                {name: 'laptop', path: mdiLaptop},
                {name: 'monitor', path: mdiMonitor},
                {name: 'printer', path: mdiPrinter},
                {name: 'wifi', path: mdiWifi},
                {name: 'download', path: mdiDownload},
                {name: 'upload', path: mdiUpload},
                {name: 'refresh', path: mdiRefresh},
                {name: 'sync', path: mdiSync},
            ],
        },
        {
            id: 'symbols',
            name: 'Symbols',
            icons: [
                {name: 'check', path: mdiCheck},
                {name: 'check-circle', path: mdiCheckCircle},
                {name: 'close', path: mdiClose},
                {name: 'plus', path: mdiPlus},
                {name: 'plus-circle', path: mdiPlusCircle},
                {name: 'minus', path: mdiMinus},
                {name: 'alert', path: mdiAlert},
                {name: 'alert-circle', path: mdiAlertCircle},
                {name: 'information', path: mdiInformation},
                {name: 'help', path: mdiHelp},
                {name: 'help-circle', path: mdiHelpCircle},
                {name: 'magnify', path: mdiMagnify},
                {name: 'filter', path: mdiFilter},
                {name: 'menu', path: mdiMenu},
                {name: 'dots-horizontal', path: mdiDotsHorizontal},
                {name: 'chevron-right', path: mdiChevronRight},
                {name: 'arrow-right', path: mdiArrowRight},
                {name: 'shield', path: mdiShield},
                {name: 'security', path: mdiSecurity},
                {name: 'safe', path: mdiSafe},
                {name: 'archive', path: mdiArchive},
                {name: 'trash-can', path: mdiTrashCan},
                {name: 'history', path: mdiHistory},
            ],
        },
    ],
};
