comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: "uncovered_patch" # only post comment if the patch has uncovered lines
  hide_project_coverage: true # only show coverage on the git diff
coverage:
  status:
    changes: false
    patch: false
    project:
      default:
        threshold: 1.0
codecov:
  notify:
    after_n_builds: 2 # Server and webapp at this point
ignore:
  - ^store/storetest.*
