comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: "uncovered_patch" # only post comment if the patch has uncovered lines
  hide_project_coverage: true # only show coverage on the git diff
coverage:
  status:
    changes: false
    patch: false
    project:
      default:
        threshold: 1.0
flags:
  server:
    after_n_builds: 4 # 4 server test shards
  webapp:
    after_n_builds: 1 # 1 merged webapp upload
ignore:
  - ^store/storetest.*
