// Code generated by mockery v2.42.2. DO NOT EDIT.

// Regenerate this file using `make einterfaces-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	request "github.com/mattermost/mattermost/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// PolicyAdministrationPointInterface is an autogenerated mock type for the PolicyAdministrationPointInterface type
type PolicyAdministrationPointInterface struct {
	mock.Mock
}

// CheckExpression provides a mock function with given fields: rctx, expression
func (_m *PolicyAdministrationPointInterface) CheckExpression(rctx request.CTX, expression string) ([]model.CELExpressionError, *model.AppError) {
	ret := _m.Called(rctx, expression)

	if len(ret) == 0 {
		panic("no return value specified for CheckExpression")
	}

	var r0 []model.CELExpressionError
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(request.CTX, string) ([]model.CELExpressionError, *model.AppError)); ok {
		return rf(rctx, expression)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, string) []model.CELExpressionError); ok {
		r0 = rf(rctx, expression)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CELExpressionError)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, string) *model.AppError); ok {
		r1 = rf(rctx, expression)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// DeletePolicy provides a mock function with given fields: rctx, id
func (_m *PolicyAdministrationPointInterface) DeletePolicy(rctx request.CTX, id string) *model.AppError {
	ret := _m.Called(rctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePolicy")
	}

	var r0 *model.AppError
	if rf, ok := ret.Get(0).(func(request.CTX, string) *model.AppError); ok {
		r0 = rf(rctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AppError)
		}
	}

	return r0
}

// ExtractAttributeFields provides a mock function with given fields: rctx, targetType, expression
func (_m *PolicyAdministrationPointInterface) ExtractAttributeFields(rctx request.CTX, targetType string, expression string) ([]string, *model.AppError) {
	ret := _m.Called(rctx, targetType, expression)

	if len(ret) == 0 {
		panic("no return value specified for ExtractAttributeFields")
	}

	var r0 []string
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(request.CTX, string, string) ([]string, *model.AppError)); ok {
		return rf(rctx, targetType, expression)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, string, string) []string); ok {
		r0 = rf(rctx, targetType, expression)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, string, string) *model.AppError); ok {
		r1 = rf(rctx, targetType, expression)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// GetBasicAutocomplete provides a mock function with given fields: rctx, targetType
func (_m *PolicyAdministrationPointInterface) GetBasicAutocomplete(rctx request.CTX, targetType string) (map[string]interface{}, *model.AppError) {
	ret := _m.Called(rctx, targetType)

	if len(ret) == 0 {
		panic("no return value specified for GetBasicAutocomplete")
	}

	var r0 map[string]interface{}
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(request.CTX, string) (map[string]interface{}, *model.AppError)); ok {
		return rf(rctx, targetType)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, string) map[string]interface{}); ok {
		r0 = rf(rctx, targetType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, string) *model.AppError); ok {
		r1 = rf(rctx, targetType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// GetPolicy provides a mock function with given fields: rctx, id
func (_m *PolicyAdministrationPointInterface) GetPolicy(rctx request.CTX, id string) (*model.AccessControlPolicy, *model.AppError) {
	ret := _m.Called(rctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPolicy")
	}

	var r0 *model.AccessControlPolicy
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(request.CTX, string) (*model.AccessControlPolicy, *model.AppError)); ok {
		return rf(rctx, id)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, string) *model.AccessControlPolicy); ok {
		r0 = rf(rctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccessControlPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, string) *model.AppError); ok {
		r1 = rf(rctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// Init provides a mock function with given fields: rctx
func (_m *PolicyAdministrationPointInterface) Init(rctx request.CTX) *model.AppError {
	ret := _m.Called(rctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 *model.AppError
	if rf, ok := ret.Get(0).(func(request.CTX) *model.AppError); ok {
		r0 = rf(rctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AppError)
		}
	}

	return r0
}

// SavePolicy provides a mock function with given fields: rctx, policy
func (_m *PolicyAdministrationPointInterface) SavePolicy(rctx request.CTX, policy *model.AccessControlPolicy) (*model.AccessControlPolicy, *model.AppError) {
	ret := _m.Called(rctx, policy)

	if len(ret) == 0 {
		panic("no return value specified for SavePolicy")
	}

	var r0 *model.AccessControlPolicy
	var r1 *model.AppError
	if rf, ok := ret.Get(0).(func(request.CTX, *model.AccessControlPolicy) (*model.AccessControlPolicy, *model.AppError)); ok {
		return rf(rctx, policy)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, *model.AccessControlPolicy) *model.AccessControlPolicy); ok {
		r0 = rf(rctx, policy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccessControlPolicy)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, *model.AccessControlPolicy) *model.AppError); ok {
		r1 = rf(rctx, policy)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*model.AppError)
		}
	}

	return r0, r1
}

// NewPolicyAdministrationPointInterface creates a new instance of PolicyAdministrationPointInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPolicyAdministrationPointInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PolicyAdministrationPointInterface {
	mock := &PolicyAdministrationPointInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
