// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

export default {
    GET_PAGES_REQUEST: 'GET_PAGES_REQUEST',
    GET_PAGES_SUCCESS: 'GET_PAGES_SUCCESS',
    GET_PAGES_FAILURE: 'GET_PAGES_FAILURE',
    RECEIVED_PAGE_IN_WIKI: 'RECEIVED_PAGE_IN_WIKI',
    DELETED_PAGE: 'DELETED_PAGE',
    RECEIVED_WIKI: 'RECEIVED_WIKI',
    DELETED_WIKI: 'DELETED_WIKI',
    RECEIVED_DRAFT: 'RECEIVED_DRAFT',
    DELETED_DRAFT: 'DELETED_DRAFT',
    PUBLISH_DRAFT_REQUEST: 'PUBLISH_DRAFT_REQUEST',
    PUBLISH_DRAFT_SUCCESS: 'PUBLISH_DRAFT_SUCCESS',
    PUBLISH_DRAFT_FAILURE: 'PUBLISH_DRAFT_FAILURE',
    PUBLISH_DRAFT_COMPLETED: 'PUBLISH_DRAFT_COMPLETED',
    INVALIDATE_PAGES: 'INVALIDATE_PAGES',
};
