// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

export default {
    GET_WIKI_PAGES_REQUEST: 'GET_WIKI_PAGES_REQUEST',
    GET_WIKI_PAGES_SUCCESS: 'GET_WIKI_PAGES_SUCCESS',
    GET_WIKI_PAGES_FAILURE: 'GET_WIKI_PAGES_FAILURE',
    RECEIVED_PAGE: 'RECEIVED_PAGE',
    DELETED_PAGE: 'DELETED_PAGE',
    RECEIVED_DRAFT: 'RECEIVED_DRAFT',
    DELETED_DRAFT: 'DELETED_DRAFT',
    PUBLISH_DRAFT_REQUEST: 'PUBLISH_DRAFT_REQUEST',
    PUBLISH_DRAFT_SUCCESS: 'PUBLISH_DRAFT_SUCCESS',
    PUBLISH_DRAFT_FAILURE: 'PUBLISH_DRAFT_FAILURE',
    PUBLISH_DRAFT_COMPLETED: 'PUBLISH_DRAFT_COMPLETED',
};
