// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

export default {
    GET_PAGES_REQUEST: 'GET_PAGES_REQUEST',
    GET_PAGES_SUCCESS: 'GET_PAGES_SUCCESS',
    GET_PAGES_FAILURE: 'GET_PAGES_FAILURE',
    RECEIVED_PAGE_IN_WIKI: 'RECEIVED_PAGE_IN_WIKI',
    REMOVED_PAGE_FROM_WIKI: 'REMOVED_PAGE_FROM_WIKI',
    DELETED_PAGE: 'DELETED_PAGE',
    RECEIVED_WIKI: 'RECEIVED_WIKI',
    RECEIVED_WIKIS: 'RECEIVED_WIKIS',
    DELETED_WIKI: 'DELETED_WIKI',
    RECEIVED_DRAFT: 'RECEIVED_DRAFT',
    DELETED_DRAFT: 'DELETED_DRAFT',
    PUBLISH_DRAFT_REQUEST: 'PUBLISH_DRAFT_REQUEST',
    PUBLISH_DRAFT_SUCCESS: 'PUBLISH_DRAFT_SUCCESS',
    PUBLISH_DRAFT_FAILURE: 'PUBLISH_DRAFT_FAILURE',
    PUBLISH_DRAFT_COMPLETED: 'PUBLISH_DRAFT_COMPLETED',
    INVALIDATE_PAGES: 'INVALIDATE_PAGES',
    INVALIDATE_DRAFTS: 'INVALIDATE_DRAFTS',
    RECEIVED_PAGE_STATUS_FIELD: 'RECEIVED_PAGE_STATUS_FIELD',
    RECEIVED_PAGE_STATUS: 'RECEIVED_PAGE_STATUS',
    CLEANUP_PUBLISHED_DRAFT_TIMESTAMPS: 'CLEANUP_PUBLISHED_DRAFT_TIMESTAMPS',
    DRAFT_DELETION_RECORDED: 'DRAFT_DELETION_RECORDED',
    DRAFT_DELETION_REVERTED: 'DRAFT_DELETION_REVERTED',
    CLEANUP_DELETED_DRAFT_TIMESTAMPS: 'CLEANUP_DELETED_DRAFT_TIMESTAMPS',
};
