name: "Web app setup"
description: "Set up NPM and dependencies"

runs:
  using: "composite"
  steps:
    - name: ci/setup-node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      id: setup_node
      with:
        node-version-file: ".nvmrc"
        cache: npm
        cache-dependency-path: 'webapp/package-lock.json'
    - name: ci/get-node-modules
      shell: bash
      working-directory: webapp
      run: |
        make node_modules
