name: "Web app setup"
description: "Set up NPM and dependencies"

runs:
  using: "composite"
  steps:
    - name: ci/setup-node
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: ".nvmrc"
    - name: ci/cache-node-modules
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache-node-modules
      with:
        path: |
          webapp/node_modules
          webapp/channels/node_modules
          webapp/platform/client/node_modules
          webapp/platform/components/node_modules
          webapp/platform/shared/node_modules
          webapp/platform/types/node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('webapp/package-lock.json') }}
    - name: ci/get-node-modules
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      working-directory: webapp
      run: |
        make node_modules
    - name: ci/build-platform-packages
      # These are built automatically when depenedencies are installed, but they aren't cached properly, so we need to
      # manually build them when the cache is hit. They aren't worth caching because they have too many dependencies.
      if: steps.cache-node-modules.outputs.cache-hit == 'true'
      shell: bash
      working-directory: webapp
      run: |
        npm run postinstall
