// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import mock "github.com/stretchr/testify/mock"

// ServiceTermsStore is an autogenerated mock type for the ServiceTermsStore type
type ServiceTermsStore struct {
	mock.Mock
}
