// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import xor from 'lodash.xor';

// *****************************************************************************
// Preferences
// https://api.mattermost.com/#tag/roles
// *****************************************************************************

export const defaultRolesPermissions = {
    channel_admin: [
        'create_post',
        'manage_private_channel_members',
        'read_public_channel_groups',
        'manage_channel_roles',
        'use_channel_mentions',
        'use_group_mentions',
        'read_private_channel_groups',
        'remove_reaction',
        'add_reaction',
        'manage_public_channel_members',
    ],
    channel_guest: [
        'remove_reaction',
        'upload_file',
        'create_post',
        'use_channel_mentions',
        'use_slash_commands',
        'read_channel',
        'add_reaction',
        'edit_post',
    ],
    channel_user: [
        'remove_reaction',
        'use_slash_commands',
        'edit_post',
        'read_public_channel_groups',
        'delete_post',
        'read_private_channel_groups',
        'manage_public_channel_properties',
        'manage_public_channel_members',
        'delete_private_channel',
        'manage_private_channel_members',
        'manage_private_channel_properties',
        'use_channel_mentions',
        'create_post',
        'delete_public_channel',
        'use_group_mentions',
        'upload_file',
        'add_reaction',
        'read_channel',
        'get_public_link',
    ],
    sysadmin: [
        'read_user_access_token',
        'manage_incoming_webhooks',
        'delete_public_channel',
        'create_direct_channel',
        'list_private_teams',
        'sysconsole_write_user_management_channels',
        'sysconsole_write_authentication_signup',
        'sysconsole_write_authentication_email',
        'sysconsole_write_authentication_password',
        'sysconsole_write_authentication_mfa',
        'sysconsole_write_authentication_ldap',
        'sysconsole_write_authentication_saml',
        'sysconsole_write_authentication_openid',
        'sysconsole_write_authentication_guest_access',
        'add_reaction',
        'list_users_without_team',
        'read_others_bots',
        'convert_private_channel_to_public',
        'sysconsole_read_user_management_permissions',
        'edit_post',
        'edit_other_users',
        'manage_team',
        'convert_public_channel_to_private',
        'sysconsole_write_user_management_users',
        'manage_system_wide_oauth',
        'manage_private_channel_members',
        'revoke_user_access_token',
        'sysconsole_read_authentication_signup',
        'sysconsole_read_authentication_email',
        'sysconsole_read_authentication_password',
        'sysconsole_read_authentication_mfa',
        'sysconsole_read_authentication_ldap',
        'sysconsole_read_authentication_saml',
        'sysconsole_read_authentication_openid',
        'sysconsole_read_authentication_guest_access',
        'read_private_channel_groups',
        'manage_bots',
        'delete_private_channel',
        'create_group_channel',
        'add_user_to_team',
        'manage_others_slash_commands',
        'sysconsole_read_user_management_teams',
        'sysconsole_read_site_customization',
        'sysconsole_read_site_localization',
        'sysconsole_read_site_users_and_teams',
        'sysconsole_read_site_notifications',
        'sysconsole_read_site_announcement_banner',
        'sysconsole_read_site_emoji',
        'sysconsole_read_site_posts',
        'sysconsole_read_site_file_sharing_and_downloads',
        'sysconsole_read_site_public_links',
        'sysconsole_read_site_notices',
        'read_public_channel_groups',
        'view_members',
        'remove_others_reactions',
        'sysconsole_write_reporting_site_statistics',
        'sysconsole_write_reporting_server_logs',
        'sysconsole_write_reporting_team_statistics',
        'list_team_channels',
        'create_private_channel',
        'read_channel',
        'create_public_channel',
        'use_slash_commands',
        'sysconsole_write_site_customization',
        'sysconsole_write_site_localization',
        'sysconsole_write_site_users_and_teams',
        'sysconsole_write_site_notifications',
        'sysconsole_write_site_announcement_banner',
        'sysconsole_write_site_emoji',
        'sysconsole_write_site_posts',
        'sysconsole_write_site_file_sharing_and_downloads',
        'sysconsole_write_site_public_links',
        'sysconsole_write_site_notices',
        'sysconsole_write_user_management_groups',
        'read_jobs',
        'sysconsole_write_user_management_permissions',
        'create_bot',
        'sysconsole_read_user_management_channels',
        'use_group_mentions',
        'manage_public_channel_properties',
        'manage_others_bots',
        'manage_channel_roles',
        'assign_bot',
        'assign_system_admin_role',
        'create_user_access_token',
        'sysconsole_write_plugins',
        'manage_system',
        'demote_to_guest',
        'manage_others_incoming_webhooks',
        'view_team',
        'delete_post',
        'promote_guest',
        'manage_public_channel_members',
        'sysconsole_write_user_management_teams',
        'invite_user',
        'join_private_teams',
        'upload_file',
        'edit_others_posts',
        'delete_others_posts',
        'list_public_teams',
        'read_public_channel',
        'read_bots',
        'sysconsole_read_plugins',
        'manage_team_roles',
        'create_emojis',
        'sysconsole_read_user_management_groups',
        'join_public_channels',
        'create_post',
        'remove_reaction',
        'manage_slash_commands',
        'get_public_link',
        'sysconsole_read_environment_web_server',
        'sysconsole_read_environment_database',
        'sysconsole_read_environment_elasticsearch',
        'sysconsole_read_environment_file_storage',
        'sysconsole_read_environment_image_proxy',
        'sysconsole_read_environment_smtp',
        'sysconsole_read_environment_push_notification_server',
        'sysconsole_read_environment_high_availability',
        'sysconsole_read_environment_rate_limiting',
        'sysconsole_read_environment_logging',
        'sysconsole_read_environment_session_lengths',
        'sysconsole_read_environment_performance_monitoring',
        'sysconsole_read_environment_developer',
        'sysconsole_write_environment_web_server',
        'sysconsole_write_environment_database',
        'sysconsole_write_environment_elasticsearch',
        'sysconsole_write_environment_file_storage',
        'sysconsole_write_environment_image_proxy',
        'sysconsole_write_environment_smtp',
        'sysconsole_write_environment_push_notification_server',
        'sysconsole_write_environment_high_availability',
        'sysconsole_write_environment_rate_limiting',
        'sysconsole_write_environment_logging',
        'sysconsole_write_environment_session_lengths',
        'sysconsole_write_environment_performance_monitoring',
        'sysconsole_write_environment_developer',
        'test_site_url',
        'test_elasticsearch',
        'test_s3',
        'test_email',
        'reload_config',
        'invalidate_caches',
        'purge_elasticsearch_indexes',
        'recycle_database_connections',
        'create_elasticsearch_post_indexing_job',
        'create_elasticsearch_post_aggregation_job',
        'read_elasticsearch_post_indexing_job',
        'read_elasticsearch_post_aggregation_job',
        'read_other_users_teams',
        'manage_private_channel_properties',
        'manage_oauth',
        'remove_user_from_team',
        'create_post_ephemeral',
        'delete_emojis',
        'sysconsole_read_user_management_users',
        'manage_jobs',
        'create_team',
        'manage_roles',
        'sysconsole_read_reporting_server_logs',
        'sysconsole_read_reporting_site_statistics',
        'sysconsole_read_reporting_team_statistics',
        'get_logs',
        'get_analytics',
        'edit_brand',
        'use_channel_mentions',
        'delete_others_emojis',
        'invite_guest',
        'manage_others_outgoing_webhooks',
        'create_post_public',
        'manage_outgoing_webhooks',
        'import_team',
        'join_public_teams',
        'sysconsole_read_integrations_integration_management',
        'sysconsole_read_integrations_bot_accounts',
        'sysconsole_read_integrations_gif',
        'sysconsole_read_integrations_cors',
        'sysconsole_write_integrations_integration_management',
        'sysconsole_write_integrations_bot_accounts',
        'sysconsole_write_integrations_gif',
        'sysconsole_write_integrations_cors',
        'sysconsole_read_experimental_features',
        'sysconsole_read_experimental_feature_flags',
        'sysconsole_read_experimental_bleve',
        'sysconsole_write_experimental_features',
        'sysconsole_write_experimental_feature_flags',
        'sysconsole_write_experimental_bleve',
        'purge_bleve_indexes',
        'post_bleve_indexes',
        'create_ldap_sync_job',
        'read_ldap_sync_job',
        'test_ldap',
        'invalidate_email_invite',
        'get_saml_metadata_from_idp',
        'add_saml_public_cert',
        'add_saml_private_cert',
        'add_saml_idp_cert',
        'remove_saml_public_cert',
        'remove_saml_private_cert',
        'remove_saml_idp_cert',
        'get_saml_cert_status',
        'add_ldap_public_cert',
        'add_ldap_private_cert',
        'remove_ldap_public_cert',
        'remove_ldap_private_cert',
        'sysconsole_read_compliance_data_retention_policy',
        'sysconsole_read_compliance_compliance_export',
        'sysconsole_read_compliance_compliance_monitoring',
        'sysconsole_read_compliance_custom_terms_of_service',
        'sysconsole_write_compliance_data_retention_policy',
        'sysconsole_write_compliance_compliance_export',
        'sysconsole_write_compliance_compliance_monitoring',
        'sysconsole_write_compliance_custom_terms_of_service',
        'create_data_retention_job',
        'read_data_retention_job',
        'create_compliance_export_job',
        'read_compliance_export_job',
        'read_audits',
        'sysconsole_read_about_edition_and_license',
        'sysconsole_write_about_edition_and_license',
        'read_license_information',
        'manage_license_information',
    ],
    system_guest: [
        'create_direct_channel',
        'create_group_channel',
    ],
    system_manager: [
        'read_public_channel_groups',
        'read_channel',
        'sysconsole_write_user_management_channels',
        'manage_private_channel_properties',
        'add_user_to_team',
        'manage_private_channel_members',
        'sysconsole_write_user_management_teams',
        'convert_private_channel_to_public',
        'manage_public_channel_members',
        'remove_user_from_team',
        'manage_team_roles',
        'sysconsole_read_user_management_groups',
        'manage_channel_roles',
        'list_private_teams',
        'sysconsole_read_authentication_signup',
        'sysconsole_read_authentication_email',
        'sysconsole_read_authentication_password',
        'sysconsole_read_authentication_mfa',
        'sysconsole_read_authentication_ldap',
        'read_ldap_sync_job',
        'sysconsole_read_authentication_saml',
        'sysconsole_read_authentication_openid',
        'sysconsole_read_authentication_guest_access',
        'manage_jobs',
        'read_jobs',
        'sysconsole_read_plugins',
        'manage_public_channel_properties',
        'list_public_teams',
        'sysconsole_write_user_management_groups',
        'read_private_channel_groups',
        'delete_public_channel',
        'sysconsole_write_site_customization',
        'sysconsole_write_site_localization',
        'sysconsole_write_site_users_and_teams',
        'sysconsole_write_site_notifications',
        'sysconsole_write_site_announcement_banner',
        'sysconsole_write_site_emoji',
        'sysconsole_write_site_posts',
        'sysconsole_write_site_file_sharing_and_downloads',
        'sysconsole_write_site_public_links',
        'sysconsole_write_site_notices',
        'sysconsole_read_user_management_channels',
        'sysconsole_read_user_management_teams',
        'sysconsole_write_user_management_permissions',
        'sysconsole_read_site_customization',
        'sysconsole_read_site_localization',
        'sysconsole_read_site_users_and_teams',
        'sysconsole_read_site_notifications',
        'sysconsole_read_site_announcement_banner',
        'sysconsole_read_site_emoji',
        'sysconsole_read_site_posts',
        'sysconsole_read_site_file_sharing_and_downloads',
        'sysconsole_read_site_public_links',
        'sysconsole_read_site_notices',
        'sysconsole_read_about_edition_and_license',
        'read_license_information',
        'sysconsole_read_reporting_server_logs',
        'sysconsole_read_reporting_site_statistics',
        'sysconsole_read_reporting_team_statistics',
        'get_logs',
        'get_analytics',
        'sysconsole_read_integrations_integration_management',
        'sysconsole_read_integrations_bot_accounts',
        'sysconsole_read_integrations_gif',
        'sysconsole_read_integrations_cors',
        'sysconsole_write_integrations_integration_management',
        'sysconsole_write_integrations_bot_accounts',
        'sysconsole_write_integrations_gif',
        'sysconsole_write_integrations_cors',
        'view_team',
        'convert_public_channel_to_private',
        'join_public_teams',
        'read_public_channel',
        'edit_brand',
        'join_private_teams',
        'sysconsole_read_user_management_permissions',
        'manage_team',
        'delete_private_channel',
        'sysconsole_read_environment_web_server',
        'sysconsole_read_environment_database',
        'sysconsole_read_environment_elasticsearch',
        'sysconsole_read_environment_file_storage',
        'sysconsole_read_environment_image_proxy',
        'sysconsole_read_environment_smtp',
        'sysconsole_read_environment_push_notification_server',
        'sysconsole_read_environment_high_availability',
        'sysconsole_read_environment_rate_limiting',
        'sysconsole_read_environment_logging',
        'sysconsole_read_environment_session_lengths',
        'sysconsole_read_environment_performance_monitoring',
        'sysconsole_read_environment_developer',
        'sysconsole_write_environment_web_server',
        'sysconsole_write_environment_database',
        'sysconsole_write_environment_elasticsearch',
        'sysconsole_write_environment_file_storage',
        'sysconsole_write_environment_image_proxy',
        'sysconsole_write_environment_smtp',
        'sysconsole_write_environment_push_notification_server',
        'sysconsole_write_environment_high_availability',
        'sysconsole_write_environment_rate_limiting',
        'sysconsole_write_environment_logging',
        'sysconsole_write_environment_session_lengths',
        'sysconsole_write_environment_performance_monitoring',
        'sysconsole_write_environment_developer',
        'test_site_url',
        'test_elasticsearch',
        'test_s3',
        'test_email',
        'reload_config',
        'invalidate_caches',
        'purge_elasticsearch_indexes',
        'recycle_database_connections',
        'create_elasticsearch_post_indexing_job',
        'create_elasticsearch_post_aggregation_job',
        'read_elasticsearch_post_indexing_job',
        'read_elasticsearch_post_aggregation_job',
    ],
    system_post_all: [
        'use_group_mentions',
        'use_channel_mentions',
        'create_post',
    ],
    system_post_all_public: [
        'use_group_mentions',
        'use_channel_mentions',
        'create_post_public',
    ],
    system_read_only_admin: [
        'list_private_teams',
        'list_public_teams',
        'read_public_channel_groups',
        'read_channel',
        'sysconsole_read_user_management_users',
        'read_other_users_teams',
        'sysconsole_read_user_management_permissions',
        'sysconsole_read_site_customization',
        'sysconsole_read_site_localization',
        'sysconsole_read_site_users_and_teams',
        'sysconsole_read_site_notifications',
        'sysconsole_read_site_announcement_banner',
        'sysconsole_read_site_emoji',
        'sysconsole_read_site_posts',
        'sysconsole_read_site_file_sharing_and_downloads',
        'sysconsole_read_site_public_links',
        'sysconsole_read_site_notices',
        'sysconsole_read_user_management_channels',
        'sysconsole_read_about',
        'sysconsole_read_authentication_signup',
        'sysconsole_read_authentication_email',
        'sysconsole_read_authentication_password',
        'sysconsole_read_authentication_mfa',
        'sysconsole_read_authentication_ldap',
        'read_ldap_sync_job',
        'sysconsole_read_authentication_saml',
        'sysconsole_read_authentication_openid',
        'sysconsole_read_authentication_guest_access',
        'sysconsole_read_about_edition_and_license',
        'read_license_information',
        'sysconsole_read_user_management_teams',
        'sysconsole_read_user_management_groups',
        'sysconsole_read_plugins',
        'sysconsole_read_reporting_server_logs',
        'sysconsole_read_reporting_site_statistics',
        'sysconsole_read_reporting_team_statistics',
        'get_logs',
        'get_analytics',
        'read_jobs',
        'read_private_channel_groups',
        'view_team',
        'sysconsole_read_environment_web_server',
        'sysconsole_read_environment_database',
        'sysconsole_read_environment_elasticsearch',
        'sysconsole_read_environment_file_storage',
        'sysconsole_read_environment_image_proxy',
        'sysconsole_read_environment_smtp',
        'sysconsole_read_environment_push_notification_server',
        'sysconsole_read_environment_high_availability',
        'sysconsole_read_environment_rate_limiting',
        'sysconsole_read_environment_logging',
        'sysconsole_read_environment_session_lengths',
        'sysconsole_read_environment_performance_monitoring',
        'sysconsole_read_environment_developer',
        'read_elasticsearch_post_indexing_job',
        'read_elasticsearch_post_aggregation_job',
        'read_public_channel',
        'sysconsole_read_integrations_integration_management',
        'sysconsole_read_integrations_bot_accounts',
        'sysconsole_read_integrations_gif',
        'sysconsole_read_integrations_cors',
        'sysconsole_read_compliance_data_retention_policy',
        'sysconsole_read_compliance_compliance_export',
        'sysconsole_read_compliance_compliance_monitoring',
        'sysconsole_read_compliance_custom_terms_of_service',
        'sysconsole_read_experimental_features',
        'sysconsole_read_experimental_feature_flags',
        'sysconsole_read_experimental_bleve',
    ],
    system_user: [
        'list_public_teams',
        'join_public_teams',
        'create_direct_channel',
        'create_group_channel',
        'create_team',
        'view_members',
        'create_emojis',
        'delete_emojis',
    ],
    system_user_access_token: [
        'revoke_user_access_token',
        'create_user_access_token',
        'read_user_access_token',
    ],
    system_user_manager: [
        'manage_private_channel_members',
        'manage_team_roles',
        'manage_public_channel_members',
        'read_channel',
        'read_public_channel_groups',
        'sysconsole_read_user_management_teams',
        'list_public_teams',
        'manage_private_channel_properties',
        'sysconsole_read_user_management_groups',
        'manage_team',
        'sysconsole_write_user_management_channels',
        'read_private_channel_groups',
        'list_private_teams',
        'sysconsole_write_user_management_teams',
        'remove_user_from_team',
        'delete_public_channel',
        'sysconsole_read_authentication_signup',
        'sysconsole_read_authentication_email',
        'sysconsole_read_authentication_password',
        'sysconsole_read_authentication_mfa',
        'sysconsole_read_authentication_ldap',
        'read_ldap_sync_job',
        'sysconsole_read_authentication_saml',
        'sysconsole_read_authentication_openid',
        'sysconsole_read_authentication_guest_access',
        'convert_public_channel_to_private',
        'join_private_teams',
        'add_user_to_team',
        'sysconsole_read_user_management_permissions',
        'join_public_teams',
        'read_public_channel',
        'manage_public_channel_properties',
        'convert_private_channel_to_public',
        'manage_channel_roles',
        'read_jobs',
        'sysconsole_read_user_management_channels',
        'delete_private_channel',
        'view_team',
        'sysconsole_write_user_management_groups',
    ],
    team_admin: [
        'manage_private_channel_members',
        'delete_others_posts',
        'import_team',
        'convert_private_channel_to_public',
        'manage_incoming_webhooks',
        'delete_post',
        'create_post',
        'manage_others_outgoing_webhooks',
        'manage_others_incoming_webhooks',
        'manage_outgoing_webhooks',
        'manage_team',
        'manage_slash_commands',
        'read_private_channel_groups',
        'remove_user_from_team',
        'manage_channel_roles',
        'use_channel_mentions',
        'convert_public_channel_to_private',
        'manage_team_roles',
        'use_group_mentions',
        'read_public_channel_groups',
        'add_reaction',
        'manage_public_channel_members',
        'remove_reaction',
        'manage_others_slash_commands',
    ],
    team_guest: ['view_team'],
    team_post_all: [
        'use_channel_mentions',
        'use_group_mentions',
        'create_post',
    ],
    team_post_all_public: [
        'use_channel_mentions',
        'use_group_mentions',
        'create_post_public',
    ],
    team_user: [
        'list_team_channels',
        'join_public_channels',
        'read_public_channel',
        'view_team',
        'create_public_channel',
        'create_private_channel',
        'invite_user',
        'add_user_to_team',
    ],
};

Cypress.Commands.add('getRoleByName', (name) => {
    return cy.request({
        headers: {'X-Requested-With': 'XMLHttpRequest'},
        url: `/api/v4/roles/name/${name}`,
        method: 'GET',
    }).then((response) => {
        expect(response.status).to.equal(200);
        return cy.wrap({name: response.body});
    });
});

Cypress.Commands.add('apiGetRolesByNames', (names) => {
    return cy.request({
        headers: {'X-Requested-With': 'XMLHttpRequest'},
        url: '/api/v4/roles/names',
        method: 'POST',
        body: names || Object.keys(defaultRolesPermissions),
    }).then((response) => {
        expect(response.status).to.equal(200);
        return cy.wrap({roles: response.body});
    });
});

Cypress.Commands.add('apiPatchRole', (roleID, patch) => {
    return cy.request({
        headers: {'X-Requested-With': 'XMLHttpRequest'},
        url: `/api/v4/roles/${roleID}/patch`,
        method: 'PUT',
        body: patch,
    }).then((response) => {
        expect(response.status).to.equal(200);
        return cy.wrap({role: response.body});
    });
});

Cypress.Commands.add('apiResetRoles', () => {
    cy.apiGetRolesByNames().then(({roles}) => {
        roles.forEach((role) => {
            const defaultPermissions = defaultRolesPermissions[role.name];
            const diff = xor(role.permissions, defaultPermissions);

            if (diff.length > 0) {
                cy.apiPatchRole(role.id, {permissions: defaultPermissions});
            }
        });
    });
});
