#!/usr/bin/env ts-node

/**
 * Push Automation Status to Zephyr
 *
 * Simple script to update Zephyr when E2E test is created.
 * No AI needed - just API calls!
 *
 * Usage:
 *   npm run push-to-zephyr MM-T5382
 *   npm run push-to-zephyr -- --batch (updates all automated tests)
 */

import * as dotenv from 'dotenv';
import * as path from 'path';
import * as fs from 'fs';
import {createZephyrAPI} from '../lib/zephyr-api';
import {validateZephyrConfig} from '../config/zephyr.config';

// Load environment variables from the playwright directory
dotenv.config({path: path.join(__dirname, '../.env')});

async function pushToZephyr(testKey: string, e2eFilePath?: string) {
    console.log(`📤 Updating ${testKey} in Zephyr...\n`);

    // Validate config
    try {
        validateZephyrConfig();
    } catch (error: any) {
        console.error('❌ Configuration error:', error.message);
        process.exit(1);
    }

    const zephyrAPI = createZephyrAPI();

    // If no file path provided, try to find it
    if (!e2eFilePath) {
        const foundFilePath = findE2ETestFile(testKey);
        if (!foundFilePath) {
            console.error(`❌ Could not find E2E test file for ${testKey}`);
            console.error('   Please provide file path as second argument');
            process.exit(1);
        }
        e2eFilePath = foundFilePath;
    }

    console.log(`📁 E2E File: ${e2eFilePath}`);

    try {
        // Mark as automated
        await zephyrAPI.markAsAutomated(testKey, e2eFilePath);
        console.log(`✅ Marked as automated`);

        // Add comment
        const comment = `E2E test automated on ${new Date().toISOString()}\n` +
                       `File: ${e2eFilePath}\n` +
                       `Generated by: automated script`;

        await zephyrAPI.addComment(testKey, comment);
        console.log(`✅ Added comment`);

        console.log(`\n✅ Successfully updated ${testKey} in Zephyr!`);
        console.log(`   View in Zephyr: ${process.env.ZEPHYR_BASE_URL}/testcase/${testKey}`);

    } catch (error: any) {
        console.error('❌ Error updating Zephyr:', error.message);
        process.exit(1);
    }
}

function findE2ETestFile(testKey: string): string | null {
    const specsDir = path.join(__dirname, '../specs');

    // Search recursively for test file containing the test key
    const files = findFilesRecursive(specsDir, '.spec.ts');

    for (const file of files) {
        const content = fs.readFileSync(file, 'utf-8');
        if (content.includes(testKey)) {
            // Return relative path from specs directory
            return path.relative(path.join(__dirname, '..'), file);
        }
    }

    return null;
}

function findFilesRecursive(dir: string, ext: string): string[] {
    let results: string[] = [];

    const files = fs.readdirSync(dir);

    files.forEach(file => {
        const filePath = path.join(dir, file);
        const stat = fs.statSync(filePath);

        if (stat.isDirectory()) {
            results = results.concat(findFilesRecursive(filePath, ext));
        } else if (file.endsWith(ext)) {
            results.push(filePath);
        }
    });

    return results;
}

// Batch update function
async function batchUpdate() {
    console.log('📦 Batch updating all automated tests...\n');

    const specsDir = path.join(__dirname, '../specs');
    const testFiles = findFilesRecursive(specsDir, '.spec.ts');

    let updated = 0;
    let failed = 0;

    for (const file of testFiles) {
        const content = fs.readFileSync(file, 'utf-8');

        // Extract MM-T keys from test titles
        const matches = content.matchAll(/test\(['"`]([M-T\d]+)/g);

        for (const match of matches) {
            const testKey = match[1];
            const relativePath = path.relative(path.join(__dirname, '..'), file);

            try {
                await pushToZephyr(testKey, relativePath);
                updated++;
            } catch (error: any) {
                console.error(`❌ Failed to update ${testKey}:`, error.message);
                failed++;
            }
        }
    }

    console.log(`\n=== Batch Update Complete ===`);
    console.log(`✅ Updated: ${updated}`);
    console.log(`❌ Failed: ${failed}`);
}

// Main execution
const args = process.argv.slice(2);

if (args.includes('--batch')) {
    batchUpdate().catch((error: any) => {
        console.error('❌ Batch update error:', error.message);
        process.exit(1);
    });
} else {
    const testKey = args[0];
    const filePath = args[1];

    if (!testKey) {
        console.error('Usage: npm run push-to-zephyr MM-TXXX [file-path]');
        console.error('   or: npm run push-to-zephyr -- --batch');
        process.exit(1);
    }

    pushToZephyr(testKey, filePath).catch((error: any) => {
        console.error('❌ Error:', error.message);
        process.exit(1);
    });
}
