// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import type {Theme, ThemeKey} from 'mattermost-redux/selectors/entities/preferences';

const Preferences = {
    APP_BAR: 'app_bar',
    CATEGORY_CHANNEL_OPEN_TIME: 'channel_open_time',
    CATEGORY_CHANNEL_APPROXIMATE_VIEW_TIME: 'channel_approximate_view_time',
    CATEGORY_DIRECT_CHANNEL_SHOW: 'direct_channel_show',
    CATEGORY_GROUP_CHANNEL_SHOW: 'group_channel_show',
    CATEGORY_FLAGGED_POST: 'flagged_post',
    CATEGORY_AUTO_RESET_MANUAL_STATUS: 'auto_reset_manual_status',
    CATEGORY_NOTIFICATIONS: 'notifications',
    COLLAPSED_REPLY_THREADS: 'collapsed_reply_threads',
    COLLAPSED_REPLY_THREADS_OFF: 'off',
    COLLAPSED_REPLY_THREADS_ON: 'on',
    COLLAPSED_REPLY_THREADS_FALLBACK_DEFAULT: 'off',
    COMMENTS: 'comments',
    COMMENTS_ANY: 'any',
    COMMENTS_ROOT: 'root',
    COMMENTS_NEVER: 'never',
    EMAIL: 'email',
    EMAIL_INTERVAL: 'email_interval',
    INTERVAL_FIFTEEN_MINUTES: 15 * 60,
    INTERVAL_HOUR: 60 * 60,
    INTERVAL_IMMEDIATE: 30,

    // "immediate" is a 30 second interval
    INTERVAL_NEVER: 0,
    INTERVAL_NOT_SET: -1,
    CATEGORY_DISPLAY_SETTINGS: 'display_settings',
    NAME_NAME_FORMAT: 'name_format',
    DISPLAY_PREFER_NICKNAME: 'nickname_full_name',
    DISPLAY_PREFER_FULL_NAME: 'full_name',
    DISPLAY_PREFER_USERNAME: 'username',
    MENTION_KEYS: 'mention_keys',
    USE_MILITARY_TIME: 'use_military_time',

    CATEGORY_CUSTOM_STATUS: 'custom_status',
    NAME_CUSTOM_STATUS_TUTORIAL_STATE: 'custom_status_tutorial_state',
    NAME_RECENT_CUSTOM_STATUSES: 'recent_custom_statuses',
    CUSTOM_STATUS_MODAL_VIEWED: 'custom_status_modal_viewed',

    CATEGORY_SIDEBAR_SETTINGS: 'sidebar_settings',
    CHANNEL_SIDEBAR_ORGANIZATION: 'channel_sidebar_organization',
    LIMIT_VISIBLE_DMS_GMS: 'limit_visible_dms_gms',
    SHOW_UNREAD_SECTION: 'show_unread_section',
    CATEGORY_ADVANCED_SETTINGS: 'advanced_settings',
    ADVANCED_FILTER_JOIN_LEAVE: 'join_leave',
    RENDER_EMOTICONS_AS_EMOJI: 'render_emoticons_as_emoji',
    ADVANCED_CODE_BLOCK_ON_CTRL_ENTER: 'code_block_ctrl_enter',
    ADVANCED_SEND_ON_CTRL_ENTER: 'send_on_ctrl_enter',
    ADVANCED_SYNC_DRAFTS: 'sync_drafts',
    CATEGORY_WHATS_NEW_MODAL: 'whats_new_modal',
    HAS_SEEN_SIDEBAR_WHATS_NEW_MODAL: 'has_seen_sidebar_whats_new_modal',

    CATEGORY_PERFORMANCE_DEBUGGING: 'performance_debugging',
    NAME_DISABLE_CLIENT_PLUGINS: 'disable_client_plugins',
    NAME_DISABLE_TYPING_MESSAGES: 'disable_typing_messages',

    UNREAD_SCROLL_POSITION: 'unread_scroll_position',
    UNREAD_SCROLL_POSITION_START_FROM_LEFT: 'start_from_left_off',
    UNREAD_SCROLL_POSITION_START_FROM_NEWEST: 'start_from_newest',

    CATEGORY_UPGRADE_CLOUD: 'upgrade_cloud',
    SYSTEM_CONSOLE_LIMIT_REACHED: 'system_console_limit_reached',

    NEW_CHANNEL_WITH_BOARD_TOUR_SHOWED: 'channel_with_board_tip_showed',

    CATEGORY_ONBOARDING: 'category_onboarding',

    CATEGORY_DRAFTS: 'drafts',

    CATEGORY_REPORTING: 'reporting',

    HIDE_BATCH_EXPORT_CONFIRM_MODAL: 'hide_batch_export_confirm_modal',

    CATEGORY_OVERAGE_USERS_BANNER: 'overage_users_banner',
    CATEGORY_POST_HISTORY_LIMIT_BANNER: 'post_history_limit_banner',

    CATEGORY_BURN_ON_READ: 'burn_on_read',
    BURN_ON_READ_SKIP_CONFIRMATION: 'skip_delete_confirmation',

    CATEGORY_THEME: 'theme',
    THEMES: {
        denim: {
            type: 'Denim',
            sidebarBg: '#333132',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#454243',
            sidebarTextActiveBorder: '#1da390',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#2b292a',
            sidebarHeaderTextColor: '#ffffff',
            sidebarTeamBarBg: '#242223',
            onlineIndicator: '#1da390',
            awayIndicator: '#f99d1c',
            dndIndicator: '#d24b4e',
            mentionBg: '#ffffff',
            mentionBj: '#ffffff',
            mentionColor: '#333132',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#3f4350',
            newMessageSeparator: '#f99d1c',
            linkColor: '#1da390',
            buttonBg: '#1da390',
            buttonColor: '#ffffff',
            errorTextColor: '#d24b4e',
            mentionHighlightBg: '#ffd9a4',
            mentionHighlightLink: '#333132',
            codeTheme: 'github',
        },
        sapphire: {
            type: 'Sapphire',
            sidebarBg: '#1da390',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#3fb4a3',
            sidebarTextActiveBorder: '#f99d1c',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#198c7c',
            sidebarHeaderTextColor: '#ffffff',
            sidebarTeamBarBg: '#15786a',
            onlineIndicator: '#1da390',
            awayIndicator: '#f99d1c',
            dndIndicator: '#d24b4e',
            mentionBg: '#ffffff',
            mentionBj: '#ffffff',
            mentionColor: '#333132',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#3f4350',
            newMessageSeparator: '#f99d1c',
            linkColor: '#1da390',
            buttonBg: '#1da390',
            buttonColor: '#ffffff',
            errorTextColor: '#d24b4e',
            mentionHighlightBg: '#ffe8c8',
            mentionHighlightLink: '#333132',
            codeTheme: 'github',
        },
        quartz: {
            type: 'Quartz',
            sidebarBg: '#f2f2f2',
            sidebarText: '#333132',
            sidebarUnreadText: '#333132',
            sidebarTextHoverBg: '#e3e4e5',
            sidebarTextActiveBorder: '#1da390',
            sidebarTextActiveColor: '#333132',
            sidebarHeaderBg: '#e0e1e2',
            sidebarHeaderTextColor: '#333132',
            sidebarTeamBarBg: '#d6d8da',
            onlineIndicator: '#1da390',
            awayIndicator: '#f99d1c',
            dndIndicator: '#d24b4e',
            mentionBg: '#1da390',
            mentionBj: '#1da390',
            mentionColor: '#ffffff',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#3f4350',
            newMessageSeparator: '#f99d1c',
            linkColor: '#1da390',
            buttonBg: '#1da390',
            buttonColor: '#ffffff',
            errorTextColor: '#d24b4e',
            mentionHighlightBg: '#ffe8c8',
            mentionHighlightLink: '#333132',
            codeTheme: 'github',
        },
        indigo: {
            type: 'Indigo',
            sidebarBg: '#2a2829',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#3a3738',
            sidebarTextActiveBorder: '#f99d1c',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#252324',
            sidebarHeaderTextColor: '#ffffff',
            sidebarTeamBarBg: '#1f1e1f',
            onlineIndicator: '#1da390',
            awayIndicator: '#f99d1c',
            dndIndicator: '#d24b4e',
            mentionBg: '#1da390',
            mentionBj: '#1da390',
            mentionColor: '#ffffff',
            centerChannelBg: '#1f2021',
            centerChannelColor: '#dddfe4',
            newMessageSeparator: '#f99d1c',
            linkColor: '#62cbbb',
            buttonBg: '#1da390',
            buttonColor: '#ffffff',
            errorTextColor: '#d24b4e',
            mentionHighlightBg: '#5f3f0e',
            mentionHighlightLink: '#ffe1b4',
            codeTheme: 'solarized-dark',
        },
        onyx: {
            type: 'Onyx',
            sidebarBg: '#333132',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#3f3d3e',
            sidebarTextActiveBorder: '#f99d1c',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#2c2a2b',
            sidebarHeaderTextColor: '#ffffff',
            sidebarTeamBarBg: '#262425',
            onlineIndicator: '#1da390',
            awayIndicator: '#f99d1c',
            dndIndicator: '#d24b4e',
            mentionBg: '#1da390',
            mentionBj: '#1da390',
            mentionColor: '#ffffff',
            centerChannelBg: '#232527',
            centerChannelColor: '#e3e4e8',
            newMessageSeparator: '#f99d1c',
            linkColor: '#62cbbb',
            buttonBg: '#1da390',
            buttonColor: '#ffffff',
            errorTextColor: '#e06a6d',
            mentionHighlightBg: '#6b4810',
            mentionHighlightLink: '#ffe1b4',
            codeTheme: 'monokai',
        },
    } as Record<ThemeKey, Theme>,
    RECENT_EMOJIS: 'recent_emojis',
};

export default Preferences;
