// Code generated by mockery v1.0.0. DO NOT EDIT.

// Regenerate this file using `make einterfaces-mocks`.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenBucket is an autogenerated mock type for the TokenBucket type
type TokenBucket struct {
	mock.Mock
}

// Take provides a mock function with given fields:
func (_m *TokenBucket) Take() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
