DO
$$
BEGIN
    IF NOT EXISTS (
        SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
        WHERE TABLE_NAME = 'ir_timelineevent' 
        AND CONSTRAINT_TYPE = 'PRIMARY KEY' 
        AND TABLE_CATALOG = (SELECT CURRENT_DATABASE())
    ) THEN
        ALTER TABLE IR_TimelineEvent ADD PRIMARY KEY (ID);
	END IF;
END
$$;
