DO
$$
BEGIN
    IF EXISTS (
        SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
        WHERE TABLE_NAME = 'ir_viewedchannel' 
        AND CONSTRAINT_TYPE = 'PRIMARY KEY' 
        AND TABLE_CATALOG = (SELECT CURRENT_DATABASE())
    ) THEN
        ALTER TABLE IR_ViewedChannel DROP CONSTRAINT ir_viewedchannel_pkey;
	END IF;
END
$$;
