with-expecter: false
packages:
  github.com/mattermost/mattermost/server/v8/channels/store:
    config:
      include-regex: ".*Store"
      dir: "channels/store/storetest/mocks"
      filename: "{{.InterfaceName}}.go"
      mockname: "{{.InterfaceName}}"
      outpkg: mocks
      note: "Regenerate this file using `make store-mocks`."
