// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import formatjsPlugin from 'eslint-plugin-formatjs';
import noOnlyTestsPlugin from 'eslint-plugin-no-only-tests';

import eslintPlugin from '@mattermost/eslint-plugin';

export default [
    ...eslintPlugin.configs.react,
    {
        plugins: {
            formatjs: formatjsPlugin,
        },
        rules: {
            'react/prop-types': [
                2,
                {
                    ignore: [
                        'location',
                        'history',
                        'component',
                    ],
                },
            ],
            'react/no-unknown-property': [
                2,
                {
                    ignore: [
                        'mask-type',
                    ],
                },
            ],
            'react/style-prop-object': [2, {
                allow: ['Timestamp'],
            }],
            'formatjs/enforce-default-message': 2,
            'formatjs/enforce-id': 2,
            'formatjs/enforce-placeholders': 2,
            'formatjs/no-invalid-icu': 2,
            'formatjs/no-multiple-plurals': 1,
            'formatjs/no-multiple-whitespaces': 2,
            'formatjs/no-literal-string-in-jsx': 1,
            'formatjs/prefer-formatted-message': 1,
            'formatjs/no-useless-message': 1,
            'formatjs/prefer-pound-in-plural': 0,
            'react/jsx-fragments': ['error', 'syntax'],
        },
    },
    {
        files: ['**/*.test.js', '**/*.test.jsx', '**/*.test.ts', '**/*.test.tsx'],
        plugins: {
            'no-only-tests': noOnlyTestsPlugin,
        },
        rules: {
            'no-only-tests/no-only-tests': ['error', {focus: ['only', 'skip']}],
        },
    },
    {
        ignores: ['src/packages/mattermost-redux/**'],
        rules: {
            '@typescript-eslint/no-restricted-imports': [
                'error',
                {
                    paths: [{
                        name: 'mattermost-redux/types/actions',
                        importNames: ['DispatchFunc', 'GetStateFunc', 'ActionFunc', 'ActionFuncAsync', 'ThunkActionFunc'],
                        message: 'Use the web app version of it from types/store',
                    }],
                    patterns: [{
                        group: ['@mattermost/client/src/*', '@mattermost/components/src/*', '@mattermost/types/src/*'],
                        message: "Don't include the src folder when importing from packages in webapp/platform",
                    }],
                },
            ],
        },
    },

    // typescript-eslint v8 upgrade baseline: existing violations disabled
    // per-rule x per-file so they can be fixed incrementally. Do not add new files here.
    {
        files: [
            'src/components/channel_header_menu/menu_items/close_channel.tsx',
            'src/components/emoji_picker/components/emoji_picker_category_or_emoji_row.tsx',
        ],
        rules: {
            '@typescript-eslint/no-empty-object-type': 'off',
        },
    },
    {
        files: [
            'src/actions/integration_actions.test.ts',
            'src/actions/views/create_comment.test.jsx',
            'src/actions/views/rhs.test.ts',
            'src/actions/websocket_actions.test.jsx',
            'src/components/add_user_to_channel_modal/add_user_to_channel_modal.test.tsx',
            'src/components/admin_console/access_control/policy_details/policy_details.test.tsx',
            'src/components/admin_console/feature_discovery/features/data_spillage.test.tsx',
            'src/components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.test.tsx',
            'src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.test.tsx',
            'src/components/admin_console/permission_schemes_settings/permissions_tree_playbooks.test.tsx',
            'src/components/admin_console/system_user_detail/team_list/abstract_list.test.tsx',
            'src/components/admin_console/team_channel_settings/channel/list/admin_channel_shared_indicator.test.tsx',
            'src/components/advanced_text_editor/rewrite_menu.test.tsx',
            'src/components/advanced_text_editor/use_burn_on_read.test.tsx',
            'src/components/announcement_bar/post_history_limit_banner/post_history_limit_banner.test.tsx',
            'src/components/autocomplete_selector.test.tsx',
            'src/components/channel_header/channel_header_title_favorite.test.tsx',
            'src/components/channel_header_menu/menu_items/add_channel_members.test.tsx',
            'src/components/channel_header_menu/menu_items/add_group_members.test.tsx',
            'src/components/channel_header_menu/menu_items/archive_channel.test.tsx',
            'src/components/channel_header_menu/menu_items/convert_gm_to_private.test.tsx',
            'src/components/channel_header_menu/menu_items/edit_conversation_header.test.tsx',
            'src/components/channel_header_menu/menu_items/groups.test.tsx',
            'src/components/channel_header_menu/menu_items/leave_channel.test.tsx',
            'src/components/channel_header_menu/menu_items/mobile_channel_header_plugins.test.tsx',
            'src/components/channel_header_menu/menu_items/notification.test.tsx',
            'src/components/channel_header_menu/menu_items/open_member_rhs.test.tsx',
            'src/components/channel_header_menu/menu_items/toggle_favorite_channel.test.tsx',
            'src/components/channel_header_menu/menu_items/toggle_info.test.tsx',
            'src/components/channel_header_menu/menu_items/toggle_mute_channel.test.tsx',
            'src/components/channel_header_menu/menu_items/unarchive_channel.test.tsx',
            'src/components/channel_header_menu/menu_items/view_pinned_posts.test.tsx',
            'src/components/channel_invite_modal/channel_invite_modal.test.tsx',
            'src/components/channel_settings_modal/channel_settings_access_rules_activity_warning.test.tsx',
            'src/components/channel_settings_modal/channel_settings_access_rules_tab.test.tsx',
            'src/components/channel_settings_modal/channel_settings_archive_tab.test.tsx',
            'src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx',
            'src/components/channel_settings_modal/channel_settings_info_tab.test.tsx',
            'src/components/channel_settings_modal/channel_settings_modal.test.tsx',
            'src/components/channel_settings_modal/share_channel_with_workspaces/share_channel_with_workspaces.test.tsx',
            'src/components/channel_settings_modal/share_channel_with_workspaces/workspace_list.test.tsx',
            'src/components/common/hooks/useAccessControlAttributes.test.tsx',
            'src/components/datetime_input/datetime_input.test.tsx',
            'src/components/dialog_router/dialog_router.test.tsx',
            'src/components/dialog_router/interactive_dialog_adapter.test.tsx',
            'src/components/drafts/drafts_link/drafts_link.test.tsx',
            'src/components/feature_restricted_modal/feature_restricted_modal.test.tsx',
            'src/components/integrations/installed_command.test.tsx',
            'src/components/integrations/installed_oauth_apps/installed_oauth_apps.test.tsx',
            'src/components/integrations/installed_outgoing_webhooks/installed_outgoing_webhooks.test.tsx',
            'src/components/post_view/data_spillage_report/data_spillage_footer/data_spillage_footer.test.tsx',
            'src/components/post_view/data_spillage_report/data_spillage_report.test.tsx',
            'src/components/post_view/post_list_virtualized/post_list_virtualized.test.tsx',
            'src/components/post_view/post_time/post_time.test.tsx',
            'src/components/profile_popover/profile_popover.test.tsx',
            'src/components/recaps/recap_channel_card.test.tsx',
            'src/components/recaps/recap_item.test.tsx',
            'src/components/remove_flagged_message_confirmation_modal/remove_flagged_message_confirmation_modal.test.tsx',
            'src/components/rhs_plugin_popout/rhs_plugin_popout.test.tsx',
            'src/components/sidebar/sidebar_channel/sidebar_base_channel/sidebar_base_channel.test.tsx',
            'src/components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.test.tsx',
            'src/components/sidebar/sidebar_list/sidebar_list.test.tsx',
            'src/components/textbox.test.tsx',
            'src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx',
            'src/components/widgets/advanced_textbox/advanced_textbox.test.tsx',
            'src/packages/mattermost-redux/src/store/index.ts',
            'src/plugins/export.ts',
            'src/plugins/textbox/index.test.tsx',
            'src/selectors/views/channel_settings.test.ts',
            'src/tests/react-intl_mock.ts',
            'src/tests/redux-persist_mock.ts',
            'src/tests/setup_jest.ts',
            'src/utils/admin_console_index.test.tsx',
            'src/utils/notifications.test.ts',
            'src/utils/utils.tsx',
        ],
        rules: {
            '@typescript-eslint/no-require-imports': 'off',
        },
    },
    {
        files: [
            'src/actions/cloud.tsx',
            'src/actions/file_actions.ts',
            'src/actions/invite_actions.ts',
            'src/actions/marketplace.ts',
            'src/components/admin_console/access_control/policies.tsx',
            'src/components/admin_console/access_control/policy_details/channel_list/channel_list.tsx',
            'src/components/admin_console/ip_filtering/ip_filtering_utils.ts',
            'src/components/admin_console/schema_admin_settings.tsx',
            'src/components/admin_console/system_users/index.ts',
            'src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx',
            'src/components/admin_console/types.ts',
            'src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.tsx',
            'src/components/browse_channels/browse_channels.tsx',
            'src/components/channel_bookmarks/channel_bookmarks_create_modal.tsx',
            'src/components/channel_settings_modal/channel_settings_access_rules_tab.tsx',
            'src/components/code_preview.tsx',
            'src/components/common/hooks/useAccessControlAttributes.test.tsx',
            'src/components/common/hooks/useCopyText.ts',
            'src/components/create_recap_modal/create_recap_modal.tsx',
            'src/components/edit_channel_header_modal/index.ts',
            'src/components/get_link_modal.tsx',
            'src/components/inline_entity_link/utils.ts',
            'src/components/invitation_modal/invitation_modal.tsx',
            'src/components/latex_block/latex_block.tsx',
            'src/components/latex_inline/latex_inline.tsx',
            'src/components/linking_landing_page/linking_landing_page.tsx',
            'src/components/mobile_sidebar_right/index.ts',
            'src/components/new_channel_modal/new_channel_modal.tsx',
            'src/components/permalink_view/actions.ts',
            'src/components/plugin_marketplace/marketplace_item/marketplace_item_plugin/marketplace_item_plugin.tsx',
            'src/components/preparing_workspace/preparing_workspace.tsx',
            'src/components/profile_popover/profile_popover_other_user_row.tsx',
            'src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx',
            'src/components/widgets/inputs/users_emails_input.tsx',
            'src/hooks/useChannelSystemPolicies.ts',
            'src/hooks/useGetCloudPreviewModalContent.ts',
            'src/packages/mattermost-redux/src/actions/errors.ts',
            'src/packages/mattermost-redux/src/actions/general.ts',
            'src/packages/mattermost-redux/src/actions/roles.ts',
            'src/packages/mattermost-redux/src/actions/users.ts',
            'src/selectors/views/custom_status.ts',
            'src/stores/browser_store.tsx',
            'src/utils/date_utils.ts',
            'src/utils/embed.tsx',
            'src/utils/message_html_to_component.tsx',
            'src/utils/notifications.ts',
            'src/utils/syntax_highlighting.tsx',
            'src/utils/url.tsx',
            'src/utils/utils.tsx',
        ],
        rules: {
            '@typescript-eslint/no-unused-vars': 'off',
        },
    },
    {
        settings: {
            'import/resolver': 'webpack',
            formatjs: {
                additionalFunctionNames: ['localizeMessage', 'defineMessage'],
            },
        },
    },
];
