CREATE TABLE IF NOT EXISTS IR_Playbook (
    ID VARCHAR(26) PRIMARY KEY,
    Title VARCHAR(1024) NOT NULL,
    Description VARCHAR(4096) NOT NULL,
    TeamID VARCHAR(26) NOT NULL,
    CreatePublicIncident BOOLEAN NOT NULL,
    CreateAt BIGINT NOT NULL,
    DeleteAt BIGINT NOT NULL DEFAULT 0,
    ChecklistsJSON TEXT NOT NULL,
    NumStages BIGINT NOT NULL DEFAULT 0,
    NumSteps BIGINT NOT NULL DEFAULT 0,
    INDEX IR_Playbook_TeamID (TeamID),
    INDEX IR_PlaybookMember_PlaybookID (ID)
) DEFAULT CHARACTER SET utf8mb4;
