CREATE TABLE IF NOT EXISTS IR_Incident (
	ID VARCHAR(26) PRIMARY KEY,
	Name VARCHAR(1024) NOT NULL,
	Description VARCHAR(4096) NOT NULL,
	IsActive BOOLEAN NOT NULL,
	CommanderUserID VARCHAR(26) NOT NULL,
	TeamID VARCHAR(26) NOT NULL,
	ChannelID VARCHAR(26) NOT NULL UNIQUE,
	CreateAt BIGINT NOT NULL,
	EndAt BIGINT NOT NULL DEFAULT 0,
	DeleteAt BIGINT NOT NULL DEFAULT 0,
	ActiveStage BIGINT NOT NULL,
	PostID VARCHAR(26) NOT NULL DEFAULT '',
	PlaybookID VARCHAR(26) NOT NULL DEFAULT '',
	ChecklistsJSON TEXT NOT NULL,
	INDEX IR_Incident_TeamID (TeamID),
	INDEX IR_Incident_TeamID_CommanderUserID (TeamID, CommanderUserID),
	INDEX IR_Incident_ChannelID (ChannelID)
) DEFAULT CHARACTER SET utf8mb4;
