"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
See LICENSE.txt for license information.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import common_pb2 as _common_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class KVSetRequest(_message.Message):
    """===========================================================================
    KV Store Methods
    ===========================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVSetRequest: _TypeAlias = KVSetRequest  # noqa: Y015

@_typing.final
class KVSetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVSetResponse: _TypeAlias = KVSetResponse  # noqa: Y015

@_typing.final
class KVCompareAndSetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    OLD_VALUE_FIELD_NUMBER: _builtins.int
    NEW_VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    old_value: _builtins.bytes
    new_value: _builtins.bytes
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        old_value: _builtins.bytes = ...,
        new_value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "new_value", b"new_value", "old_value", b"old_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVCompareAndSetRequest: _TypeAlias = KVCompareAndSetRequest  # noqa: Y015

@_typing.final
class KVCompareAndSetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVCompareAndSetResponse: _TypeAlias = KVCompareAndSetResponse  # noqa: Y015

@_typing.final
class KVCompareAndDeleteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    OLD_VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    old_value: _builtins.bytes
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        old_value: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "old_value", b"old_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVCompareAndDeleteRequest: _TypeAlias = KVCompareAndDeleteRequest  # noqa: Y015

@_typing.final
class KVCompareAndDeleteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVCompareAndDeleteResponse: _TypeAlias = KVCompareAndDeleteResponse  # noqa: Y015

@_typing.final
class KVSetWithOptionsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    @_builtins.property
    def options(self) -> Global___PluginKVSetOptions: ...
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
        options: Global___PluginKVSetOptions | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["options", b"options"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "options", b"options", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVSetWithOptionsRequest: _TypeAlias = KVSetWithOptionsRequest  # noqa: Y015

@_typing.final
class KVSetWithOptionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVSetWithOptionsResponse: _TypeAlias = KVSetWithOptionsResponse  # noqa: Y015

@_typing.final
class KVSetWithExpiryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    EXPIRE_IN_SECONDS_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.bytes
    expire_in_seconds: _builtins.int
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.bytes = ...,
        expire_in_seconds: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expire_in_seconds", b"expire_in_seconds", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVSetWithExpiryRequest: _TypeAlias = KVSetWithExpiryRequest  # noqa: Y015

@_typing.final
class KVSetWithExpiryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVSetWithExpiryResponse: _TypeAlias = KVSetWithExpiryResponse  # noqa: Y015

@_typing.final
class KVGetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVGetRequest: _TypeAlias = KVGetRequest  # noqa: Y015

@_typing.final
class KVGetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    value: _builtins.bytes
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVGetResponse: _TypeAlias = KVGetResponse  # noqa: Y015

@_typing.final
class KVDeleteRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVDeleteRequest: _TypeAlias = KVDeleteRequest  # noqa: Y015

@_typing.final
class KVDeleteResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVDeleteResponse: _TypeAlias = KVDeleteResponse  # noqa: Y015

@_typing.final
class KVDeleteAllRequest(_message.Message):
    """Empty request - deletes all keys for the plugin"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___KVDeleteAllRequest: _TypeAlias = KVDeleteAllRequest  # noqa: Y015

@_typing.final
class KVDeleteAllResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVDeleteAllResponse: _TypeAlias = KVDeleteAllResponse  # noqa: Y015

@_typing.final
class KVListRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGE_FIELD_NUMBER: _builtins.int
    PER_PAGE_FIELD_NUMBER: _builtins.int
    page: _builtins.int
    per_page: _builtins.int
    def __init__(
        self,
        *,
        page: _builtins.int = ...,
        per_page: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page", b"page", "per_page", b"per_page"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVListRequest: _TypeAlias = KVListRequest  # noqa: Y015

@_typing.final
class KVListResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    KEYS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    @_builtins.property
    def keys(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        keys: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "keys", b"keys"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KVListResponse: _TypeAlias = KVListResponse  # noqa: Y015

@_typing.final
class PublishWebSocketEventRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENT_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    BROADCAST_FIELD_NUMBER: _builtins.int
    event: _builtins.str
    @_builtins.property
    def payload(self) -> _struct_pb2.Struct: ...
    @_builtins.property
    def broadcast(self) -> Global___WebsocketBroadcast: ...
    def __init__(
        self,
        *,
        event: _builtins.str = ...,
        payload: _struct_pb2.Struct | None = ...,
        broadcast: Global___WebsocketBroadcast | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["broadcast", b"broadcast", "payload", b"payload"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["broadcast", b"broadcast", "event", b"event", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PublishWebSocketEventRequest: _TypeAlias = PublishWebSocketEventRequest  # noqa: Y015

@_typing.final
class PublishWebSocketEventResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PublishWebSocketEventResponse: _TypeAlias = PublishWebSocketEventResponse  # noqa: Y015

@_typing.final
class LoadPluginConfigurationRequest(_message.Message):
    """===========================================================================
    Configuration Methods
    ===========================================================================

    Empty - configuration will be returned as JSON bytes
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___LoadPluginConfigurationRequest: _TypeAlias = LoadPluginConfigurationRequest  # noqa: Y015

@_typing.final
class LoadPluginConfigurationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    CONFIG_JSON_FIELD_NUMBER: _builtins.int
    config_json: _builtins.bytes
    """JSON-encoded configuration"""
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        config_json: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_json", b"config_json", "error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LoadPluginConfigurationResponse: _TypeAlias = LoadPluginConfigurationResponse  # noqa: Y015

@_typing.final
class GetConfigRequest(_message.Message):
    """Empty"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetConfigRequest: _TypeAlias = GetConfigRequest  # noqa: Y015

@_typing.final
class GetConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    CONFIG_JSON_FIELD_NUMBER: _builtins.int
    config_json: _builtins.bytes
    """JSON-encoded model.Config"""
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        config_json: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_json", b"config_json", "error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetConfigResponse: _TypeAlias = GetConfigResponse  # noqa: Y015

@_typing.final
class GetUnsanitizedConfigRequest(_message.Message):
    """Empty"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetUnsanitizedConfigRequest: _TypeAlias = GetUnsanitizedConfigRequest  # noqa: Y015

@_typing.final
class GetUnsanitizedConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    CONFIG_JSON_FIELD_NUMBER: _builtins.int
    config_json: _builtins.bytes
    """JSON-encoded model.Config with secrets"""
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        config_json: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_json", b"config_json", "error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetUnsanitizedConfigResponse: _TypeAlias = GetUnsanitizedConfigResponse  # noqa: Y015

@_typing.final
class SaveConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_JSON_FIELD_NUMBER: _builtins.int
    config_json: _builtins.bytes
    """JSON-encoded model.Config"""
    def __init__(
        self,
        *,
        config_json: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_json", b"config_json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SaveConfigRequest: _TypeAlias = SaveConfigRequest  # noqa: Y015

@_typing.final
class SaveConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SaveConfigResponse: _TypeAlias = SaveConfigResponse  # noqa: Y015

@_typing.final
class GetPluginConfigRequest(_message.Message):
    """Empty"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetPluginConfigRequest: _TypeAlias = GetPluginConfigRequest  # noqa: Y015

@_typing.final
class GetPluginConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    @_builtins.property
    def config(self) -> _struct_pb2.Struct:
        """Plugin-specific configuration"""

    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        config: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config", "error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPluginConfigResponse: _TypeAlias = GetPluginConfigResponse  # noqa: Y015

@_typing.final
class SavePluginConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONFIG_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def config(self) -> _struct_pb2.Struct:
        """Plugin-specific configuration"""

    def __init__(
        self,
        *,
        config: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SavePluginConfigRequest: _TypeAlias = SavePluginConfigRequest  # noqa: Y015

@_typing.final
class SavePluginConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SavePluginConfigResponse: _TypeAlias = SavePluginConfigResponse  # noqa: Y015

@_typing.final
class GetBundlePathRequest(_message.Message):
    """===========================================================================
    Plugin Methods
    ===========================================================================

    Empty
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetBundlePathRequest: _TypeAlias = GetBundlePathRequest  # noqa: Y015

@_typing.final
class GetBundlePathResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "path", b"path"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetBundlePathResponse: _TypeAlias = GetBundlePathResponse  # noqa: Y015

@_typing.final
class GetPluginsRequest(_message.Message):
    """Empty"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetPluginsRequest: _TypeAlias = GetPluginsRequest  # noqa: Y015

@_typing.final
class GetPluginsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    MANIFESTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    @_builtins.property
    def manifests(self) -> _containers.RepeatedCompositeFieldContainer[Global___Manifest]: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        manifests: _abc.Iterable[Global___Manifest] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "manifests", b"manifests"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPluginsResponse: _TypeAlias = GetPluginsResponse  # noqa: Y015

@_typing.final
class EnablePluginRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EnablePluginRequest: _TypeAlias = EnablePluginRequest  # noqa: Y015

@_typing.final
class EnablePluginResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EnablePluginResponse: _TypeAlias = EnablePluginResponse  # noqa: Y015

@_typing.final
class DisablePluginRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DisablePluginRequest: _TypeAlias = DisablePluginRequest  # noqa: Y015

@_typing.final
class DisablePluginResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DisablePluginResponse: _TypeAlias = DisablePluginResponse  # noqa: Y015

@_typing.final
class RemovePluginRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RemovePluginRequest: _TypeAlias = RemovePluginRequest  # noqa: Y015

@_typing.final
class RemovePluginResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RemovePluginResponse: _TypeAlias = RemovePluginResponse  # noqa: Y015

@_typing.final
class GetPluginStatusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPluginStatusRequest: _TypeAlias = GetPluginStatusRequest  # noqa: Y015

@_typing.final
class GetPluginStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    @_builtins.property
    def status(self) -> Global___PluginStatus: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        status: Global___PluginStatus | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPluginStatusResponse: _TypeAlias = GetPluginStatusResponse  # noqa: Y015

@_typing.final
class InstallPluginRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FILE_DATA_FIELD_NUMBER: _builtins.int
    REPLACE_FIELD_NUMBER: _builtins.int
    file_data: _builtins.bytes
    replace: _builtins.bool
    def __init__(
        self,
        *,
        file_data: _builtins.bytes = ...,
        replace: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["file_data", b"file_data", "replace", b"replace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InstallPluginRequest: _TypeAlias = InstallPluginRequest  # noqa: Y015

@_typing.final
class InstallPluginResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    MANIFEST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    @_builtins.property
    def manifest(self) -> Global___Manifest: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        manifest: Global___Manifest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "manifest", b"manifest"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "manifest", b"manifest"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InstallPluginResponse: _TypeAlias = InstallPluginResponse  # noqa: Y015

@_typing.final
class GetPluginIDRequest(_message.Message):
    """Empty"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetPluginIDRequest: _TypeAlias = GetPluginIDRequest  # noqa: Y015

@_typing.final
class GetPluginIDResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    PLUGIN_ID_FIELD_NUMBER: _builtins.int
    plugin_id: _builtins.str
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
        plugin_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "plugin_id", b"plugin_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetPluginIDResponse: _TypeAlias = GetPluginIDResponse  # noqa: Y015

@_typing.final
class LogDebugRequest(_message.Message):
    """===========================================================================
    Logging Methods
    ===========================================================================
    """

    DESCRIPTOR: _descriptor.Descriptor

    MSG_FIELD_NUMBER: _builtins.int
    KEY_VALUE_PAIRS_FIELD_NUMBER: _builtins.int
    msg: _builtins.str
    @_builtins.property
    def key_value_pairs(self) -> _containers.RepeatedCompositeFieldContainer[Global___KeyValuePair]: ...
    def __init__(
        self,
        *,
        msg: _builtins.str = ...,
        key_value_pairs: _abc.Iterable[Global___KeyValuePair] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key_value_pairs", b"key_value_pairs", "msg", b"msg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogDebugRequest: _TypeAlias = LogDebugRequest  # noqa: Y015

@_typing.final
class LogDebugResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogDebugResponse: _TypeAlias = LogDebugResponse  # noqa: Y015

@_typing.final
class LogInfoRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MSG_FIELD_NUMBER: _builtins.int
    KEY_VALUE_PAIRS_FIELD_NUMBER: _builtins.int
    msg: _builtins.str
    @_builtins.property
    def key_value_pairs(self) -> _containers.RepeatedCompositeFieldContainer[Global___KeyValuePair]: ...
    def __init__(
        self,
        *,
        msg: _builtins.str = ...,
        key_value_pairs: _abc.Iterable[Global___KeyValuePair] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key_value_pairs", b"key_value_pairs", "msg", b"msg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogInfoRequest: _TypeAlias = LogInfoRequest  # noqa: Y015

@_typing.final
class LogInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogInfoResponse: _TypeAlias = LogInfoResponse  # noqa: Y015

@_typing.final
class LogErrorRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MSG_FIELD_NUMBER: _builtins.int
    KEY_VALUE_PAIRS_FIELD_NUMBER: _builtins.int
    msg: _builtins.str
    @_builtins.property
    def key_value_pairs(self) -> _containers.RepeatedCompositeFieldContainer[Global___KeyValuePair]: ...
    def __init__(
        self,
        *,
        msg: _builtins.str = ...,
        key_value_pairs: _abc.Iterable[Global___KeyValuePair] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key_value_pairs", b"key_value_pairs", "msg", b"msg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogErrorRequest: _TypeAlias = LogErrorRequest  # noqa: Y015

@_typing.final
class LogErrorResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogErrorResponse: _TypeAlias = LogErrorResponse  # noqa: Y015

@_typing.final
class LogWarnRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MSG_FIELD_NUMBER: _builtins.int
    KEY_VALUE_PAIRS_FIELD_NUMBER: _builtins.int
    msg: _builtins.str
    @_builtins.property
    def key_value_pairs(self) -> _containers.RepeatedCompositeFieldContainer[Global___KeyValuePair]: ...
    def __init__(
        self,
        *,
        msg: _builtins.str = ...,
        key_value_pairs: _abc.Iterable[Global___KeyValuePair] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key_value_pairs", b"key_value_pairs", "msg", b"msg"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogWarnRequest: _TypeAlias = LogWarnRequest  # noqa: Y015

@_typing.final
class LogWarnResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def error(self) -> _common_pb2.AppError: ...
    def __init__(
        self,
        *,
        error: _common_pb2.AppError | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___LogWarnResponse: _TypeAlias = LogWarnResponse  # noqa: Y015

@_typing.final
class PluginKVSetOptions(_message.Message):
    """===========================================================================
    Supporting Types
    ===========================================================================

    PluginKVSetOptions contains options for KVSetWithOptions.
    Maps to model.PluginKVSetOptions in Go.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ATOMIC_FIELD_NUMBER: _builtins.int
    OLD_VALUE_FIELD_NUMBER: _builtins.int
    EXPIRE_IN_SECONDS_FIELD_NUMBER: _builtins.int
    atomic: _builtins.bool
    old_value: _builtins.bytes
    expire_in_seconds: _builtins.int
    def __init__(
        self,
        *,
        atomic: _builtins.bool = ...,
        old_value: _builtins.bytes = ...,
        expire_in_seconds: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["atomic", b"atomic", "expire_in_seconds", b"expire_in_seconds", "old_value", b"old_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PluginKVSetOptions: _TypeAlias = PluginKVSetOptions  # noqa: Y015

@_typing.final
class WebsocketBroadcast(_message.Message):
    """WebsocketBroadcast determines to which users to send a websocket event.
    Maps to model.WebsocketBroadcast in Go.
    """

    DESCRIPTOR: _descriptor.Descriptor

    OMIT_USERS_FIELD_NUMBER: _builtins.int
    USER_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    TEAM_ID_FIELD_NUMBER: _builtins.int
    CONNECTION_ID_FIELD_NUMBER: _builtins.int
    OMIT_CONNECTION_ID_FIELD_NUMBER: _builtins.int
    RELIABLE_CLUSTER_SEND_FIELD_NUMBER: _builtins.int
    CONTENTION_FREE_BROADCAST_FIELD_NUMBER: _builtins.int
    user_id: _builtins.str
    channel_id: _builtins.str
    team_id: _builtins.str
    connection_id: _builtins.str
    omit_connection_id: _builtins.bool
    reliable_cluster_send: _builtins.bool
    contention_free_broadcast: _builtins.bool
    @_builtins.property
    def omit_users(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        omit_users: _abc.Iterable[_builtins.str] | None = ...,
        user_id: _builtins.str = ...,
        channel_id: _builtins.str = ...,
        team_id: _builtins.str = ...,
        connection_id: _builtins.str = ...,
        omit_connection_id: _builtins.bool = ...,
        reliable_cluster_send: _builtins.bool = ...,
        contention_free_broadcast: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "connection_id", b"connection_id", "contention_free_broadcast", b"contention_free_broadcast", "omit_connection_id", b"omit_connection_id", "omit_users", b"omit_users", "reliable_cluster_send", b"reliable_cluster_send", "team_id", b"team_id", "user_id", b"user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___WebsocketBroadcast: _TypeAlias = WebsocketBroadcast  # noqa: Y015

@_typing.final
class Manifest(_message.Message):
    """Manifest represents a plugin manifest.
    Maps to model.Manifest in Go (simplified).
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    HOMEPAGE_URL_FIELD_NUMBER: _builtins.int
    SUPPORT_URL_FIELD_NUMBER: _builtins.int
    RELEASE_NOTES_URL_FIELD_NUMBER: _builtins.int
    ICON_PATH_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    MIN_SERVER_VERSION_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    name: _builtins.str
    description: _builtins.str
    homepage_url: _builtins.str
    support_url: _builtins.str
    release_notes_url: _builtins.str
    icon_path: _builtins.str
    version: _builtins.str
    min_server_version: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        homepage_url: _builtins.str = ...,
        support_url: _builtins.str = ...,
        release_notes_url: _builtins.str = ...,
        icon_path: _builtins.str = ...,
        version: _builtins.str = ...,
        min_server_version: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "homepage_url", b"homepage_url", "icon_path", b"icon_path", "id", b"id", "min_server_version", b"min_server_version", "name", b"name", "release_notes_url", b"release_notes_url", "support_url", b"support_url", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Manifest: _TypeAlias = Manifest  # noqa: Y015

@_typing.final
class PluginStatus(_message.Message):
    """PluginStatus represents the status of a plugin.
    Maps to model.PluginStatus in Go.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PLUGIN_ID_FIELD_NUMBER: _builtins.int
    PLUGIN_PATH_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    plugin_id: _builtins.str
    plugin_path: _builtins.str
    state: _builtins.int
    """model.PluginStateNotRunning, Running, FailedToStart, etc."""
    name: _builtins.str
    description: _builtins.str
    version: _builtins.str
    def __init__(
        self,
        *,
        plugin_id: _builtins.str = ...,
        plugin_path: _builtins.str = ...,
        state: _builtins.int = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        version: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "name", b"name", "plugin_id", b"plugin_id", "plugin_path", b"plugin_path", "state", b"state", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PluginStatus: _TypeAlias = PluginStatus  # noqa: Y015

@_typing.final
class KeyValuePair(_message.Message):
    """KeyValuePair represents a key-value pair for logging."""

    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    @_builtins.property
    def value(self) -> _struct_pb2.Value: ...
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _struct_pb2.Value | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___KeyValuePair: _TypeAlias = KeyValuePair  # noqa: Y015
