import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — generated by `node docs-site/scripts/gen-documentation-sidebar.mjs`
// from the migrated content tree under docs/.
import generated from './documentation.generated.json';

// Documentation tab sidebar. Generated from the docs/ directory tree
// (Product Overview, Use Case Guide, Deployment Guide, Administration
// Guide, Security Guide, End User Guide, Integrations Guide, Get Help,
// Agents, Recipes, Samples).

const sidebars: SidebarsConfig = {
  documentation: generated as any[],
};

export default sidebars;
