ALTER TABLE commands ADD COLUMN IF NOT EXISTS allowedroles VARCHAR(1024) DEFAULT '';
ALTER TABLE commands ADD COLUMN IF NOT EXISTS allowedusers VARCHAR(1024) DEFAULT '';
ALTER TABLE commands ADD COLUMN IF NOT EXISTS allowedchannels VARCHAR(1024) DEFAULT '';
