#!/bin/sh

if [ "$(uname)" == "Darwin" ]; then
  which -s brew

  if [[ $? != 0 ]] ; then
    echo "Installing Homebrew..."
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if brew ls --versions golang-migrate > /dev/null; then
    echo "golang-migrate is already installed, skipping..."
  else
    echo "Installing golang-migrate"
    brew install golang-migrate
  fi
else
  which -s migrate

  if [[ $? != 0 ]] ; then
    echo "Installing golang-migrate"
    curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | apt-key add -
    echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list
    apt-get update
    apt-get install -y migrate
  else
    echo "golang-migrate is already installed, skipping..."
  fi
fi
