// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

/**
 * Core types for the autonomous testing system
 *
 * This file contains the essential types for specification parsing
 * and the spec-to-Playwright bridge. The heavy lifting (test generation,
 * execution, healing) is delegated to Playwright's native agents.
 */

// =============================================================================
// SPECIFICATION TYPES
// =============================================================================

/**
 * Feature Specification - parsed from specification document (PDF, MD, JSON)
 *
 * This is the primary data structure extracted from user specifications.
 * It represents a feature to be tested with its scenarios and acceptance criteria.
 */
export interface FeatureSpecification {
    /**
     * Unique identifier (derived from feature name)
     */
    id: string;

    /**
     * Feature name
     */
    name: string;

    /**
     * Feature description
     */
    description: string;

    /**
     * Priority level
     */
    priority: 'critical' | 'high' | 'medium' | 'low';

    /**
     * Target URLs to prioritize (optional - PDF specs describe behavior, not routes)
     */
    targetUrls: string[];

    /**
     * Business scenarios to test (Given-When-Then format)
     */
    scenarios: BusinessScenario[];

    /**
     * Reference screenshots from spec
     */
    screenshots: SpecScreenshot[];

    /**
     * Acceptance criteria (testable statements)
     */
    acceptanceCriteria: string[];

    /**
     * Related feature IDs
     */
    relatedFeatures?: string[];

    /**
     * Source file path
     */
    sourcePath: string;

    /**
     * Hash of source file (for cache validation)
     */
    sourceHash?: string;

    /**
     * Additional metadata (for PDFs and other formats)
     */
    metadata?: {
        /**
         * UI elements mentioned in the spec
         */
        uiElements?: string[];

        /**
         * User flows described in the spec
         */
        userFlows?: string[];

        /**
         * Source format (pdf, markdown, json, etc.)
         */
        extractedFrom?: string;

        /**
         * Any other custom metadata
         */
        [key: string]: any;
    };
}

/**
 * Business scenario from specification (Given-When-Then format)
 *
 * This format is widely used in BDD (Behavior-Driven Development)
 * and maps well to Playwright test structure.
 */
export interface BusinessScenario {
    /**
     * Scenario name (describes the test case)
     */
    name: string;

    /**
     * Given (precondition) - the initial state
     */
    given: string;

    /**
     * When (action) - the user action being tested
     */
    when: string;

    /**
     * Then (expected outcome) - the expected result
     */
    then: string;

    /**
     * Scenario priority (for test ordering)
     */
    priority: 'must-have' | 'should-have' | 'nice-to-have';

    /**
     * Test IDs that cover this scenario (populated after test generation)
     */
    coveredByTests?: string[];
}

/**
 * Specification screenshot (for visual reference)
 */
export interface SpecScreenshot {
    /**
     * File path or URL
     */
    path: string;

    /**
     * Description of what the screenshot shows
     */
    description: string;

    /**
     * Page number (for PDF screenshots)
     */
    pageNumber?: number;

    /**
     * Base64-encoded image data (loaded from path)
     */
    data?: string;
}

// =============================================================================
// TEST METADATA TYPES
// =============================================================================

/**
 * Generated test metadata
 *
 * Tracks information about tests generated from specifications.
 * The actual test code is generated by Playwright's agents.
 */
export interface GeneratedTest {
    /**
     * Unique test ID
     */
    id: string;

    /**
     * Test title
     */
    title: string;

    /**
     * Test file path
     */
    filePath: string;

    /**
     * Test code (Playwright test)
     */
    code: string;

    /**
     * Source UI states that led to this test
     */
    sourceStates: string[];

    /**
     * Related specification (if spec-driven)
     */
    relatedSpec?: {
        specId: string;
        scenarioName: string;
    };

    /**
     * AI confidence score (0.0 - 1.0)
     */
    confidence: number;

    /**
     * Test tags
     */
    tags: string[];

    /**
     * When test was generated
     */
    generatedAt: Date;

    /**
     * Generation method
     */
    generatedBy: 'playwright-planner' | 'playwright-generator' | 'manual' | 'autonomous-system' | 'spec-driven-generator';
}
