with-expecter: false
packages:
  github.com/mattermost/mattermost/server/v8/platform/shared/filestore:
    config:
      all: true
      dir: "platform/shared/filestore/mocks"
      filename: "{{.InterfaceName}}.go"
      mockname: "{{.InterfaceName}}"
      outpkg: "mocks"
      note: "Regenerate this file using `make filestore-mocks`."
