// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

import React from 'react';

interface SvgProps {
    width?: number;
    height?: number;
}

const GetAppMobileSvg = (props: SvgProps) => {
    return (
        <svg
            width={props.width ? props.width.toString() : '301'}
            height={props.height ? props.height.toString() : '663'}
            viewBox='0 0 301 663'
            fill='none'
            xmlns='http://www.w3.org/2000/svg'
        >
            <g clipPath='url(#a)'>
                <ellipse
                    cx={150.092}
                    cy={647.2}
                    fill='#000'
                    fillOpacity={0.08}
                    rx={150.092}
                    ry={15.515}
                />
                <rect
                    width={300.183}
                    height={649.251}
                    fill='#2D3039'
                    rx={35.846}
                />
                <rect
                    width={281.851}
                    height={628.628}
                    x={9.166}
                    y={9.93}
                    fill='#1E325C'
                    rx={29.739}
                />
                <mask
                    id='b'
                    width={283}
                    height={630}
                    x={9}
                    y={9}
                    maskUnits='userSpaceOnUse'
                    style={{
                        maskType: 'alpha',
                    }}
                >
                    <rect
                        width={281.851}
                        height={629.391}
                        x={9.166}
                        y={9.166}
                        fill='#1E325C'
                        rx={29.739}
                    />
                </mask>
                <g mask='url(#b)'>
                    <rect
                        width={125.513}
                        height={10.291}
                        x={78.053}
                        y={39.192}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={5.146}
                    />
                    <rect
                        width={209.861}
                        height={28.25}
                        x={72.403}
                        y={73.892}
                        fill='#fff'
                        fillOpacity={0.16}
                        rx={6.054}
                    />
                    <rect
                        width={67.953}
                        height={7.466}
                        x={109.128}
                        y={83.981}
                        fill='#fff'
                        fillOpacity={0.16}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={79.946}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={7.466}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={117.68}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={7.466}
                    />
                    <rect
                        width={132.525}
                        height={7.466}
                        x={107.111}
                        y={121.413}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <rect
                        width={80.262}
                        height={7.466}
                        x={80.979}
                        y={167.398}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={190.985}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={7.466}
                    />
                    <rect
                        width={132.525}
                        height={7.466}
                        x={107.111}
                        y={194.718}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={220.85}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={7.466}
                    />
                    <rect
                        width={90.805}
                        height={8.072}
                        x={107.111}
                        y={224.28}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={4.036}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={250.714}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={7.466}
                    />
                    <rect
                        width={145.288}
                        height={8.072}
                        x={107.111}
                        y={254.145}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={4.036}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={280.579}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={7.466}
                    />
                    <rect
                        width={129.145}
                        height={8.072}
                        x={107.111}
                        y={284.01}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={4.036}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={310.444}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={7.466}
                    />
                    <rect
                        width={64.573}
                        height={8.072}
                        x={107.111}
                        y={313.874}
                        fill='#fff'
                        fillOpacity={0.64}
                        rx={4.036}
                    />
                    <rect
                        width={80.262}
                        height={7.466}
                        x={80.979}
                        y={360.162}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={383.749}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={7.466}
                    />
                    <rect
                        width={80.262}
                        height={7.466}
                        x={107.111}
                        y={387.481}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={413.613}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={7.466}
                    />
                    <rect
                        width={139.991}
                        height={7.466}
                        x={107.111}
                        y={417.346}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={443.478}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={7.466}
                    />
                    <rect
                        width={132.525}
                        height={7.466}
                        x={107.111}
                        y={447.211}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={473.343}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={7.466}
                    />
                    <rect
                        width={110.815}
                        height={7.466}
                        x={107.111}
                        y={477.076}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={503.208}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={7.466}
                    />
                    <rect
                        width={132.525}
                        height={7.466}
                        x={107.111}
                        y={506.941}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <rect
                        width={14.932}
                        height={14.932}
                        x={80.979}
                        y={533.073}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={7.466}
                    />
                    <rect
                        width={80.262}
                        height={7.466}
                        x={107.111}
                        y={536.806}
                        fill='#fff'
                        fillOpacity={0.24}
                        rx={3.733}
                    />
                    <path
                        fill='#192A4D'
                        d='M9.848 65.82h38.34c7.801 0 14.125 6.324 14.125 14.125v589.393H9.848V65.82Z'
                    />
                    <rect
                        width={27.187}
                        height={27.187}
                        x={21.842}
                        y={79.842}
                        fill='#386FE5'
                        rx={3.998}
                    />
                    <rect
                        width={34.383}
                        height={34.383}
                        x={18.244}
                        y={76.244}
                        stroke='#5D89EA'
                        strokeWidth={2.399}
                        rx={7.596}
                    />
                    <rect
                        width={31.984}
                        height={31.984}
                        x={19.443}
                        y={119.023}
                        fill='#F5AB00'
                        rx={6.397}
                    />
                    <rect
                        width={7.996}
                        height={7.996}
                        x={45.831}
                        y={117.424}
                        fill='#fff'
                        rx={3.998}
                    />
                    <rect
                        width={7.996}
                        height={7.996}
                        x={45.831}
                        y={117.424}
                        stroke='#192A4D'
                        strokeWidth={1.599}
                        rx={3.998}
                    />
                    <circle
                        cx={49.829}
                        cy={121.422}
                        r={3.198}
                        fill='#fff'
                    />
                    <rect
                        width={31.984}
                        height={31.984}
                        x={19.443}
                        y={160.603}
                        fill='#3DB887'
                        rx={6.397}
                    />
                    <rect
                        width={7.996}
                        height={7.996}
                        x={45.831}
                        y={159.003}
                        fill='#fff'
                        rx={3.998}
                    />
                    <rect
                        width={7.996}
                        height={7.996}
                        x={45.831}
                        y={159.003}
                        stroke='#192A4D'
                        strokeWidth={1.599}
                        rx={3.998}
                    />
                    <circle
                        cx={49.829}
                        cy={163.001}
                        r={3.198}
                        fill='#fff'
                    />
                    <path
                        fill='#fff'
                        fillOpacity={0.56}
                        d='M41.04 218.988h-4.798v4.798H34.63v-4.798h-4.798v-1.612h4.798v-4.797h1.612v4.797h4.797v1.612Z'
                    />
                    <circle
                        cx={35.436}
                        cy={44.085}
                        r={9.081}
                        fill='#fff'
                        fillOpacity={0.24}
                    />
                    <path
                        fill='#fff'
                        d='M9.848 563.701h282.505v74.662H9.848z'
                    />
                    <circle
                        cx={45.161}
                        cy={588.925}
                        r={9.081}
                        fill='#3F4350'
                        fillOpacity={0.24}
                    />
                    <circle
                        cx={97.626}
                        cy={588.925}
                        r={9.081}
                        fill='#3F4350'
                        fillOpacity={0.24}
                    />
                    <circle
                        cx={150.092}
                        cy={588.925}
                        r={9.081}
                        fill='#3F4350'
                        fillOpacity={0.24}
                    />
                    <circle
                        cx={202.557}
                        cy={588.925}
                        r={9.081}
                        fill='#3F4350'
                        fillOpacity={0.24}
                    />
                    <circle
                        cx={255.022}
                        cy={588.925}
                        r={9.081}
                        fill='#3F4350'
                        fillOpacity={0.24}
                    />
                </g>
            </g>
            <defs>
                <clipPath id='a'>
                    <path
                        fill='#fff'
                        d='M0 0h300.183v663H0z'
                    />
                </clipPath>
            </defs>
        </svg>
    );
};

export default GetAppMobileSvg;
