// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// PostReadStatusStore is an autogenerated mock type for the PostReadStatusStore type
type PostReadStatusStore struct {
	mock.Mock
}

// SaveMultiple provides a mock function with given fields: statuses
func (_m *PostReadStatusStore) SaveMultiple(statuses []*model.PostReadStatus) error {
	ret := _m.Called(statuses)

	if len(ret) == 0 {
		panic("no return value specified for SaveMultiple")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*model.PostReadStatus) error); ok {
		r0 = rf(statuses)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPostReadStatusStore creates a new instance of PostReadStatusStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostReadStatusStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostReadStatusStore {
	mock := &PostReadStatusStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
