// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	request "github.com/mattermost/mattermost/server/public/shared/request"
	mock "github.com/stretchr/testify/mock"
)

// ReadReceiptStore is an autogenerated mock type for the ReadReceiptStore type
type ReadReceiptStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: rctx, postID, userID
func (_m *ReadReceiptStore) Delete(rctx request.CTX, postID string, userID string) error {
	ret := _m.Called(rctx, postID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, string) error); ok {
		r0 = rf(rctx, postID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByPost provides a mock function with given fields: rctx, postID
func (_m *ReadReceiptStore) DeleteByPost(rctx request.CTX, postID string) error {
	ret := _m.Called(rctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPost")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(request.CTX, string) error); ok {
		r0 = rf(rctx, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: rctx, postID, userID
func (_m *ReadReceiptStore) Get(rctx request.CTX, postID string, userID string) (*model.ReadReceipt, error) {
	ret := _m.Called(rctx, postID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.ReadReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string, string) (*model.ReadReceipt, error)); ok {
		return rf(rctx, postID, userID)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, string, string) *model.ReadReceipt); ok {
		r0 = rf(rctx, postID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReadReceipt)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, string, string) error); ok {
		r1 = rf(rctx, postID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPost provides a mock function with given fields: rctx, postID
func (_m *ReadReceiptStore) GetByPost(rctx request.CTX, postID string) ([]*model.ReadReceipt, error) {
	ret := _m.Called(rctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPost")
	}

	var r0 []*model.ReadReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string) ([]*model.ReadReceipt, error)); ok {
		return rf(rctx, postID)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, string) []*model.ReadReceipt); ok {
		r0 = rf(rctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ReadReceipt)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, string) error); ok {
		r1 = rf(rctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReadCountForPost provides a mock function with given fields: rctx, postID
func (_m *ReadReceiptStore) GetReadCountForPost(rctx request.CTX, postID string) (int64, error) {
	ret := _m.Called(rctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetReadCountForPost")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, string) (int64, error)); ok {
		return rf(rctx, postID)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, string) int64); ok {
		r0 = rf(rctx, postID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(request.CTX, string) error); ok {
		r1 = rf(rctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnreadCountForPost provides a mock function with given fields: rctx, post
func (_m *ReadReceiptStore) GetUnreadCountForPost(rctx request.CTX, post *model.Post) (int64, error) {
	ret := _m.Called(rctx, post)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCountForPost")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, *model.Post) (int64, error)); ok {
		return rf(rctx, post)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, *model.Post) int64); ok {
		r0 = rf(rctx, post)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(request.CTX, *model.Post) error); ok {
		r1 = rf(rctx, post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvalidateReadReceiptForPostsCache provides a mock function with given fields: postID
func (_m *ReadReceiptStore) InvalidateReadReceiptForPostsCache(postID string) {
	_m.Called(postID)
}

// Save provides a mock function with given fields: rctx, receipt
func (_m *ReadReceiptStore) Save(rctx request.CTX, receipt *model.ReadReceipt) (*model.ReadReceipt, error) {
	ret := _m.Called(rctx, receipt)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.ReadReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, *model.ReadReceipt) (*model.ReadReceipt, error)); ok {
		return rf(rctx, receipt)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, *model.ReadReceipt) *model.ReadReceipt); ok {
		r0 = rf(rctx, receipt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReadReceipt)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, *model.ReadReceipt) error); ok {
		r1 = rf(rctx, receipt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: rctx, receipt
func (_m *ReadReceiptStore) Update(rctx request.CTX, receipt *model.ReadReceipt) (*model.ReadReceipt, error) {
	ret := _m.Called(rctx, receipt)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.ReadReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CTX, *model.ReadReceipt) (*model.ReadReceipt, error)); ok {
		return rf(rctx, receipt)
	}
	if rf, ok := ret.Get(0).(func(request.CTX, *model.ReadReceipt) *model.ReadReceipt); ok {
		r0 = rf(rctx, receipt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReadReceipt)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CTX, *model.ReadReceipt) error); ok {
		r1 = rf(rctx, receipt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReadReceiptStore creates a new instance of ReadReceiptStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReadReceiptStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReadReceiptStore {
	mock := &ReadReceiptStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
