// Code generated by mockery v2.53.4. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	model "github.com/mattermost/mattermost/server/public/model"
	mock "github.com/stretchr/testify/mock"
)

// UserAccessTokenStore is an autogenerated mock type for the UserAccessTokenStore type
type UserAccessTokenStore struct {
	mock.Mock
}

// CountNonCompliantExpiry provides a mock function with given fields: maxExpiresAt
func (_m *UserAccessTokenStore) CountNonCompliantExpiry(maxExpiresAt int64) (int64, error) {
	ret := _m.Called(maxExpiresAt)

	if len(ret) == 0 {
		panic("no return value specified for CountNonCompliantExpiry")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (int64, error)); ok {
		return rf(maxExpiresAt)
	}
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(maxExpiresAt)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(maxExpiresAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: tokenID
func (_m *UserAccessTokenStore) Delete(tokenID string) error {
	ret := _m.Called(tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAllForUser provides a mock function with given fields: userID
func (_m *UserAccessTokenStore) DeleteAllForUser(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByIds provides a mock function with given fields: tokenIDs
func (_m *UserAccessTokenStore) DeleteByIds(tokenIDs []string) (int64, error) {
	ret := _m.Called(tokenIDs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIds")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (int64, error)); ok {
		return rf(tokenIDs)
	}
	if rf, ok := ret.Get(0).(func([]string) int64); ok {
		r0 = rf(tokenIDs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(tokenIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNonCompliantExpiry provides a mock function with given fields: maxExpiresAt, limit
func (_m *UserAccessTokenStore) DeleteNonCompliantExpiry(maxExpiresAt int64, limit int) ([]string, error) {
	ret := _m.Called(maxExpiresAt, limit)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNonCompliantExpiry")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) ([]string, error)); ok {
		return rf(maxExpiresAt, limit)
	}
	if rf, ok := ret.Get(0).(func(int64, int) []string); ok {
		r0 = rf(maxExpiresAt, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(maxExpiresAt, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: tokenID
func (_m *UserAccessTokenStore) Get(tokenID string) (*model.UserAccessToken, error) {
	ret := _m.Called(tokenID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.UserAccessToken, error)); ok {
		return rf(tokenID)
	}
	if rf, ok := ret.Get(0).(func(string) *model.UserAccessToken); ok {
		r0 = rf(tokenID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: offset, limit
func (_m *UserAccessTokenStore) GetAll(offset int, limit int) ([]*model.UserAccessToken, error) {
	ret := _m.Called(offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*model.UserAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*model.UserAccessToken, error)); ok {
		return rf(offset, limit)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*model.UserAccessToken); ok {
		r0 = rf(offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserAccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByToken provides a mock function with given fields: tokenString
func (_m *UserAccessTokenStore) GetByToken(tokenString string) (*model.UserAccessToken, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for GetByToken")
	}

	var r0 *model.UserAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.UserAccessToken, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *model.UserAccessToken); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUser provides a mock function with given fields: userID, page, perPage
func (_m *UserAccessTokenStore) GetByUser(userID string, page int, perPage int) ([]*model.UserAccessToken, error) {
	ret := _m.Called(userID, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 []*model.UserAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int, int) ([]*model.UserAccessToken, error)); ok {
		return rf(userID, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(string, int, int) []*model.UserAccessToken); ok {
		r0 = rf(userID, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserAccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(userID, page, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpiredBefore provides a mock function with given fields: cutoff, limit
func (_m *UserAccessTokenStore) GetExpiredBefore(cutoff int64, limit int) ([]*model.UserAccessToken, error) {
	ret := _m.Called(cutoff, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiredBefore")
	}

	var r0 []*model.UserAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) ([]*model.UserAccessToken, error)); ok {
		return rf(cutoff, limit)
	}
	if rf, ok := ret.Get(0).(func(int64, int) []*model.UserAccessToken); ok {
		r0 = rf(cutoff, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserAccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(cutoff, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetExpiringTokens provides a mock function with given fields: now, thresholds, limit
func (_m *UserAccessTokenStore) GetExpiringTokens(now int64, thresholds []int, limit int) ([]*model.UserAccessToken, error) {
	ret := _m.Called(now, thresholds, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiringTokens")
	}

	var r0 []*model.UserAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, []int, int) ([]*model.UserAccessToken, error)); ok {
		return rf(now, thresholds, limit)
	}
	if rf, ok := ret.Get(0).(func(int64, []int, int) []*model.UserAccessToken); ok {
		r0 = rf(now, thresholds, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserAccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, []int, int) error); ok {
		r1 = rf(now, thresholds, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: token
func (_m *UserAccessTokenStore) Save(token *model.UserAccessToken) (*model.UserAccessToken, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *model.UserAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.UserAccessToken) (*model.UserAccessToken, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(*model.UserAccessToken) *model.UserAccessToken); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserAccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.UserAccessToken) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: term
func (_m *UserAccessTokenStore) Search(term string) ([]*model.UserAccessToken, error) {
	ret := _m.Called(term)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*model.UserAccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.UserAccessToken, error)); ok {
		return rf(term)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.UserAccessToken); ok {
		r0 = rf(term)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.UserAccessToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(term)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLastNotifiedAt provides a mock function with given fields: tokenID, notifiedAt
func (_m *UserAccessTokenStore) UpdateLastNotifiedAt(tokenID string, notifiedAt int64) error {
	ret := _m.Called(tokenID, notifiedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastNotifiedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64) error); ok {
		r0 = rf(tokenID, notifiedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTokenDisable provides a mock function with given fields: tokenID
func (_m *UserAccessTokenStore) UpdateTokenDisable(tokenID string) error {
	ret := _m.Called(tokenID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenDisable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTokenEnable provides a mock function with given fields: tokenID
func (_m *UserAccessTokenStore) UpdateTokenEnable(tokenID string) error {
	ret := _m.Called(tokenID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenEnable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTokenRotate provides a mock function with given fields: tokenID, newToken, expiresAt
func (_m *UserAccessTokenStore) UpdateTokenRotate(tokenID string, newToken string, expiresAt int64) error {
	ret := _m.Called(tokenID, newToken, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokenRotate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64) error); ok {
		r0 = rf(tokenID, newToken, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserAccessTokenStore creates a new instance of UserAccessTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserAccessTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserAccessTokenStore {
	mock := &UserAccessTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
