name: API

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .nvmrc
          cache: "npm"
          cache-dependency-path: api/package-lock.json

      - name: Run build
        run: make build

      - name: Checkout developer documentation repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: mattermost/mattermost-developer-documentation
          token: ${{ secrets.DEV_DOCS_TOKEN }}
          path: developer-docs

      - name: Copy OpenAPI spec
        run: |
          mkdir -p ${{ github.workspace }}/developer-docs/site/static
          cp v4/html/static/mattermost-openapi-v4.yaml ${{ github.workspace }}/developer-docs/site/static/

      - name: Commit and push changes
        if: github.ref == 'refs/heads/master'
        run: |
          cd ${{ github.workspace }}/developer-docs
          git config --global user.name "API Documentation Bot"
          git config --global user.email "apidocsbot@mattermost.com"
          git add site/static/mattermost-openapi-v4.yaml
          git commit -m "Update OpenAPI spec" || echo "No changes to commit"
          git push
