name: dev-docs-preview-env-template

on:
  workflow_call:
    inputs:
      PR_NUMBER:
        type: string
        required: true
      TRIGGERING_ACTOR:
        type: string
        required: true
      COMMIT_SHA:
        type: string
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs/developer
    env:
      PR_NUMBER: ${{ inputs.PR_NUMBER }}
      TRIGGERING_ACTOR: ${{ inputs.TRIGGERING_ACTOR }}
      COMMIT_SHA: ${{ inputs.COMMIT_SHA }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ inputs.COMMIT_SHA }}

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: docs/developer/go.mod

      - name: Build Previews
        run: |
          make hugo plugin-data
          rm -rf ./dist
          bin/hugo -F -s site --baseURL "http://mattermost-dev-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/${PR_NUMBER}/" --destination ../dist/html

      - name: Run tests
        run: make test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Preview Env
        run: aws s3 sync dist/html s3://mattermost-dev-docs-preview-pulls/${{ env.PR_NUMBER }} --delete --acl public-read --no-progress

      - name: Add comment to PR
        uses: peter-evans/create-or-update-comment@7dfe4b0aa0c4bbd06d172692ff8a9e18381d6979 # v3.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            Newest code from ${{ env.TRIGGERING_ACTOR }} has been published to [preview environment](http://mattermost-dev-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/${{ env.PR_NUMBER }}) for Git SHA ${{ env.COMMIT_SHA }}
