name: dev-docs-check-label-preview-env

on:
  pull_request:
    types: [labeled]

permissions: {}

jobs:
  check-label-preview-env:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'preview-environment')
    steps:
      - name: Set PR
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "$PR_NUMBER" > pr.txt
      - name: Save PR
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: pr.txt
          path: |
            pr.txt
