---
name: Push mirrored docker images
on:
  push:
    branches:
      - master
    paths:
      - server/scripts/mirror-docker-images.*

permissions:
  contents: read

jobs:
  build-docker:
    name: cd/Push mirrored docker images
    if: github.repository_owner == 'mattermost'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout mattermost project
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: cd/Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}
      - name: cd/Run image upload script
        env:
          IMAGES_FILE: server/scripts/mirror-docker-images.json
          DRY_RUN: no
        run: ./server/scripts/mirror-docker-images.sh
