---
name: Push mirrored docker images
on:
  push:
    branches:
      - master
    paths:
      - server/scripts/mirror-docker-images.*

permissions:
  contents: read

jobs:
  build-docker:
    name: cd/Push mirrored docker images
    if: github.repository_owner == 'mattermost'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout mattermost project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: cd/Login to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}
      - name: cd/Run image upload script
        env:
          IMAGES_FILE: server/scripts/mirror-docker-images.json
          DRY_RUN: no
        run: ./server/scripts/mirror-docker-images.sh
