name : End-to-End testing with tR
#now that we got a workflow file that manages to work on branch push
#we can make it so it sets up mattermost and runs tR tests
on:
  push:
    branches: [tR-e2e-tests, main]
  pull_request:
    branches: [tR-e2e-tests, main]
  workflow_dispatch:

jobs:
  e2e-tests-tR:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: mattermost
          POSTGRES_USER: mmuser
          POSTGRES_PASSWORD: mmuser-password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U mmuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install testrigor CLI
        run: |
          npm install -g testrigor-cli
      
      - name: Set up Mattermost image
        run: |
          docker run --name mattermost-preview -d --publish 8065:8065 --publish 8443:8443 mattermost/mattermost-preview

      - name: Run testrigor tests
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          SUITE_ID: ${{ vars.SUITE_ID }}
        run: |
          testrigor test-suite run "$SUITE_ID" --token "$CI_TOKEN" --test-cases-path e2e-tests/testrigor/testcases/**/*.txt --localhost --url http://localhost:8065
