## Upload sentry results when Server CI master push completes (via workflow_call from server-ci.yml).
name: Sentry Upload

on:
  workflow_call:
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true
      SENTRY_ORG:
        required: true
      SENTRY_PROJECT:
        required: true

permissions:
  contents: read

jobs:
  sentry:
    name: Send build info to sentry
    runs-on: ubuntu-22.04
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
    steps:
      - name: cd/Checkout mattermost project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: cd/Create Sentry release
        uses: getsentry/action-release@dab6548b3c03c4717878099e43782cf5be654289 # v3.5.0

