name: Tools CI
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
    paths:
      - "tools/mattermost-govet/**"
      - ".github/workflows/tools-ci.yml"

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.ref) || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  check-style:
    name: check-style (mattermost-govet)
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tools/mattermost-govet
    steps:
      - name: Checkout mattermost project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: tools/mattermost-govet/go.mod
      - name: Run check-style
        run: make check-style

  test:
    name: Test (mattermost-govet)
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: tools/mattermost-govet
    steps:
      - name: Checkout mattermost project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: tools/mattermost-govet/go.mod
      - name: Run tests
        run: make test
