name: Web App CI Master
on:
  push:
    branches:
      - master
      - main
      - release-*

jobs:
  master-ci:
    uses: ./.github/workflows/webapp-ci-template.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
