name: Report on master workflow failure
on:
  workflow_run:
    workflows: [Server CI Master, Web App CI Master]
    types: [completed]

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      name: Report failure
        run: |
          curl \
            --fail \
            -X POST \
            -H "Content-Type: application/json" \
            -d "{\"text\":\"#### ⚠️  ${{github.repository}}/${{ github.event.workflow_run.head_branch }} - ${{github.event.workflow_run.name}} build failure ⚠️\\nThe build is failing: [view failure](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.event.workflow_run.id}}).\\n\"}" \
            ${{ secrets.MM_COMMUNITY_DEVELOPERS_INCOMING_WEBHOOK_FROM_GH_ACTIONS }}
